/** PSS AI-PMO V22.4.0 - work evidence, related-item discovery and equipment image workflow. */
var PMO_V21 = Object.freeze({
  VERSION: '22.5.0',
  SOURCE_DATABASE_ID: '11ndvBcV0geEF7oJv1kX28BuC4_kAKnl37wUhL-Rx27g',
  TARGET_DATABASE_PROPERTY: 'PMO_V21_TARGET_DATABASE_ID',
  PROJECT_ROOT_PROPERTY: 'PMO_V21_PROJECT_ROOT_FOLDER_ID',
  DEFAULT_PROJECT_ROOT_FOLDER_ID: '16X3LA9YCYPUaNr5ClIcDk9uFqsI3girF',
  PROJECT_ARCHIVE_FOLDER_NAME: '_封存專案',
  EQUIPMENT_MEDIA_FOLDER_PROPERTY: 'PMO_V21_EQUIPMENT_MEDIA_FOLDER_ID',
  MEETING_OUTPUT_FOLDER_PROPERTY: 'PMO_V21_MEETING_OUTPUT_FOLDER_ID',
  TIME_ZONE: 'Asia/Taipei',
  MIGRATION_CONFIRM_TOKEN: 'CONFIRM_V21_MIGRATION',
  CLEAN_DATABASE_CONFIRM_TOKEN: 'CONFIRM_CREATE_CLEAN_V20',
  DRAWING_IMPORT_CONFIRM_TOKEN: 'CONFIRM_DRAWING_PROGRESS_20260814',
  CLEAN_DATABASE_ID_PROPERTY: 'PMO_V20_CLEAN_DATABASE_ID',
  CACHE_SECONDS: 180,
  MAX_UPLOAD_BYTES: 10 * 1024 * 1024,
  MAX_ATTACHMENT_FILES: 20,
  MAX_EQUIPMENT_IMAGE_BYTES: 10 * 1024 * 1024,
  MAX_EQUIPMENT_IMAGES: 12,
  LEGACY_QUOTE_IMPORT_CONFIRM_TOKEN: 'CONFIRM_IMPORT_LEGACY_QUOTES_20260814',
  QUOTE_CATALOG_IMPORT_CONFIRM_TOKEN: 'CONFIRM_IMPORT_QUOTE_CATALOG',
  WORK_STATUSES: ['事項', '目前處理', '無須追蹤', '完成'],
  ACTIVE_STATUSES: ['事項', '目前處理'],
  THURSDAY_SIGNERS: ['簡宏義','黃侯諴','陳彥均','張亭媛'],
  SHEETS: {
    LEGACY_PROJECTS: '專案清單',
    LEGACY_TASKS: '任務派工',
    LEGACY_FOLLOWUPS: '後續安排',
    LEGACY_REPORTS: '每日工作日誌',
    LEGACY_EVENTS: '事件回報',
    LEGACY_HISTORY: '專案歷程',
    LEGACY_DRAWINGS: '圖面管理',
    LEGACY_CLOUD: '雲端索引',
    LEGACY_ANNOUNCEMENTS: '公告欄',
    LEGACY_PEOPLE: '人員資料',
    LEGACY_TRAINING: '教育訓練管理',
    LEGACY_TRAINING_ARTICLES: '教育訓練',
    LEGACY_TRAINING_ATTACHMENTS: 'TRAIN_課程附件',
    LEGACY_QUOTE_ITEMS: '報價品項主檔',
    LEGACY_QUOTE_MASTER: '報價單主檔',
    LEGACY_QUOTE_LINES: '報價單明細',
    LEGACY_EQUIPMENT: '設備主檔',
    PROJECTS: 'V21_專案主檔',
    WORK: 'V21_工作事項',
    REPORTS: 'V21_回報紀錄',
    HISTORY: 'V21_專案歷程',
    DRAWINGS: 'V21_圖面狀態',
    PROJECT_USAGE: 'V21_專案使用',
    ATTACHMENTS: 'V21_附件',
    PROJECT_RELATIONS: 'V21_專案關聯',
    WORK_RELATIONS: 'V21_工作關聯',
    TRAINING: 'V21_教育訓練',
    TRAINING_ATTACHMENTS: 'V21_教育訓練附件',
    MEETING_RECORDS: 'V21_會議紀錄',
    MEETING_SNAPSHOT: 'V21_週四會議快照',
    EQUIPMENT_MEDIA: 'V21_設備媒體',
    QUOTE_ITEMS: 'V21_報價設備',
    QUOTE_MASTER: 'V21_報價主檔',
    QUOTE_LINES: 'V21_報價明細',
    QUOTE_FILES: 'V21_報價檔案',
    EQUIPMENT_PRICE_HISTORY: 'V21_設備價格案例',
    AUDIT: 'V21_SYS_操作紀錄',
    SETTINGS: 'V21_SYS_設定'
  },
  HEADERS: {
    PROJECTS: ['專案ID','專案名稱','客戶','系統類型','負責人','專案狀態','進度','雲端資料夾','圖面送審狀態','開始日','預計完成日','來源分頁','來源列','更新時間'],
    WORK: ['工作ID','專案ID','專案名稱','工作標題','工作類型','負責人','協作人','優先級','開始日','預計完成日','狀態','進度','完成內容','附件連結','來源分頁','來源ID','建立時間','更新時間'],
    REPORTS: ['回報ID','回報日期','人員','主管','專案ID','專案名稱','事件標題','完成回報','未完成問題','後續事項','附件連結','關聯工作ID','來源分頁','來源ID','建立時間','更新時間'],
    HISTORY: ['歷程ID','發生時間','專案ID','專案名稱','類型','來源分頁','來源ID','標題','內容','負責人','狀態','連結','內容雜湊'],
    DRAWINGS: ['圖面ID','專案ID','專案名稱','圖面標題','送審狀態','送審日期','審查結果','版次','附件連結','來源分頁','來源ID','更新時間'],
    PROJECT_USAGE: ['使用者','專案ID','使用次數','最後使用時間','置頂'],
    ATTACHMENTS: ['附件ID','資料類型','關聯ID','專案ID','顯示名稱','連結','原始檔名','MimeType','建立者','建立時間','更新時間'],
    PROJECT_RELATIONS: ['關聯ID','主專案ID','關聯專案ID','關聯類型','說明','建立者','建立時間','更新時間'],
    WORK_RELATIONS: ['關聯ID','工作ID','關聯工作ID','關聯專案ID','關聯類型','說明','建立者','建立時間','更新時間'],
    TRAINING: ['課程ID','課程名稱','專案ID','專案名稱','系統分類','設備分類','教材類型','版本','主教材連結','資料夾連結','適用對象','說明','狀態','建立者','建立時間','更新時間'],
    TRAINING_ATTACHMENTS: ['附件ID','課程ID','標題','類型','連結','MimeType','建立者','建立時間','更新時間'],
    MEETING_RECORDS: ['紀錄ID','會議日期','會議時間','主持人','參與人員','分類','序號','專案ID','專案名稱','事項','負責人','期限','原始狀態','追蹤狀態','主管決議與執行情形','來源檔案','來源版本','匯入時間'],
    MEETING_SNAPSHOT: ['掃描ID','掃描時間','週起日','週四日','分類','工作ID','專案ID','專案名稱','事項','負責人','期限','狀態','來源','去重鍵'],
    EQUIPMENT_MEDIA: ['品項ID','圖片連結','設備說明','更新者','更新時間'],
    QUOTE_ITEMS: ['品項ID','來源品項ID','大分類','分類','品號','品名規格','單位','成本單價','建議報價單價','供應商','備註','圖片連結','狀態','排序關鍵字','建立者','建立時間','更新時間'],
    QUOTE_MASTER: ['報價ID','報價單號','版本','狀態','報價日期','專案ID','專案名稱','客戶名稱','未稅小計','稅率','營業稅','含稅總額','備註','建立者','建立時間','更新時間'],
    QUOTE_LINES: ['明細ID','報價ID','項次','品項ID','大分類','分類','品號','品名規格','單位','數量','單價','未稅金額','備註','圖片連結'],
    QUOTE_FILES: ['檔案ID','報價ID','版本','專案ID','試算表連結','PDF連結','資料夾連結','來源報價ID','建立者','建立時間'],
    EQUIPMENT_PRICE_HISTORY: ['案例ID','品項ID','來源檔案','來源報價日','業主','工程地點','品號','品名規格','單位','數量','案例單價','案例金額','備註','匯入批次','建立者','建立時間'],
    AUDIT: ['時間','使用者','動作','資料類型','資料ID','結果','摘要'],
    SETTINGS: ['設定鍵','設定值','說明','更新時間']
  }
});

var V21_STATUS_MAP = Object.freeze({
  '事項': '事項', '未開始': '事項', '待處理': '事項', '待安排': '事項', '待確認': '事項',
  '需追蹤': '事項', '待追蹤': '事項', '卡關': '事項', '逾期': '事項', '待業務確認': '事項',
  '目前處理': '目前處理', '進行中': '目前處理', '處理中': '目前處理', '施作中': '目前處理', '修繕中': '目前處理',
  '無須追蹤': '無須追蹤', '取消': '無須追蹤', '已取消': '無須追蹤',
  '已完成': '完成', '完成': '完成', '已回報': '完成', '結案': '完成'
});

var V21_DRAWING_PATTERN = /(圖面|繪圖|審圖|送審|圖說|竣工圖|CAD|平面圖)/i;
var V21_PROJECT_STATUSES = Object.freeze(['待簽約','待議價','已成案，待下單','已下單','進行中','施作中','修繕中','待追蹤','待驗收','待請款','完成','暫停','取消','封存','一般管理']);
var V21_SYSTEM_TYPES = Object.freeze(['停車場系統','訪客系統','門禁系統','電梯梯控系統','批價機系統','在席系統','機器人系統','網路／主機整合','其他']);
var V21_PROJECT_SUBFOLDERS = Object.freeze(['01_合約訂單銷貨驗收文件','02_圖面資料','03_專案追蹤記錄','04_施工照片','05_驗收文件','06_教育訓練','07_請款文件','08_其他文件']);
