/** V21.7 quotation center: deduplicated catalog, multi-image media, imports and draft cleanup. */
function getQuoteCenterV21(payload) {
  return v21Safe_('GET_QUOTES',function(){payload=payload||{};var query=v21Text_(payload.query).toLowerCase(),catalog=v21LoadQuoteCatalog_(false);
    if(query)catalog=catalog.filter(function(item){return [item.name,item.code,item.category,item.group,item.supplier,item.note,item.models,item.sortKeyword].join(' ').toLowerCase().indexOf(query)>=0;});
    return {catalog:catalog.slice(0,400),recentQuotes:v21LoadRecentQuotes_().slice(0,60),total:catalog.length,duplicateItems:catalog.filter(function(item){return item.duplicateCount>1;}).length};
  });
}

function v21LoadQuoteCatalogRaw_(includeArchived) {
  var table=v21ReadSourceTable_(PMO_V21.SHEETS.LEGACY_QUOTE_ITEMS),map=v21HeaderMap_(table.headers),overrides=v21LoadQuoteItemOverrides_(),media=v21EquipmentMediaMap_(),items=[],seen={};
  table.rows.forEach(function(row){var id=v21Text_(v21Pick_(row,map,['品項ID']));if(!id)return;var override=overrides[id],legacyStatus=v21Text_(v21Pick_(row,map,['啟用狀態']))==='停用'?'封存':'啟用';
    var item={id:id,sourceItemId:id,custom:false,group:v21Text_(v21Pick_(row,map,['大分類'])),category:v21Text_(v21Pick_(row,map,['分類'])),code:v21Text_(v21Pick_(row,map,['品號'])),name:v21Text_(v21Pick_(row,map,['品名／規格','品名規格'])),unit:v21Text_(v21Pick_(row,map,['單位'])),cost:v21Number_(v21Pick_(row,map,['成本單價'])),price:v21Number_(v21Pick_(row,map,['建議報價單價'])),supplier:v21Text_(v21Pick_(row,map,['供應商'])),note:v21Text_(v21Pick_(row,map,['備註'])),imageUrl:'',status:legacyStatus,sortKeyword:'',history:{min:v21Number_(v21Pick_(row,map,['歷史最低價'])),max:v21Number_(v21Pick_(row,map,['歷史最高價'])),avg:v21Number_(v21Pick_(row,map,['歷史平均價'])),count:v21Number_(v21Pick_(row,map,['歷史價格筆數']))}};
    if(override)item=v21ApplyQuoteOverride_(item,override);seen[id]=true;if(includeArchived||item.status!=='封存')items.push(item);
  });
  Object.keys(overrides).forEach(function(id){if(seen[id])return;var override=overrides[id],item=v21ApplyQuoteOverride_({id:id,sourceItemId:override.sourceItemId||'',custom:true,history:{min:0,max:0,avg:0,count:0}},override);if(includeArchived||item.status!=='封存')items.push(item);});
  var equipment=v21ReadSourceTable_(PMO_V21.SHEETS.LEGACY_EQUIPMENT),equipmentMap=v21HeaderMap_(equipment.headers),installed=equipment.rows.map(function(row){return {name:v21Text_(v21Pick_(row,equipmentMap,['設備名稱'])),model:v21Text_(v21Pick_(row,equipmentMap,['型號'])),type:v21Text_(v21Pick_(row,equipmentMap,['設備類型'])),system:v21Text_(v21Pick_(row,equipmentMap,['系統分類'])),status:v21Text_(v21Pick_(row,equipmentMap,['健康狀態'])),project:v21Text_(v21Pick_(row,equipmentMap,['專案名稱']))};});
  items.forEach(function(item){var allMatches=installed.filter(function(device){var haystack=[device.name,device.model,device.type].join(' ').toLowerCase(),name=v21Text_(item.name).toLowerCase(),code=v21Text_(item.code).toLowerCase();return (name&&haystack.indexOf(name)>=0)||(code&&haystack.indexOf(code)>=0)||(device.model&&name.indexOf(device.model.toLowerCase())>=0);}),matches=allMatches.slice(0,8),itemMedia=media[item.id]||{};item.images=itemMedia.images||[];item.imageUrl=itemMedia.imageUrl||(item.images[0]&&item.images[0].url)||item.imageUrl||'';item.images.forEach(function(image){image.isCover=!!item.imageUrl&&image.url===item.imageUrl;});item.note=itemMedia.description||item.note||'';item.installedCount=allMatches.length;item.models=matches.map(function(device){return device.model;}).filter(Boolean).filter(function(value,index,array){return array.indexOf(value)===index;}).join('、');item.installedExamples=matches;item.sortKeyword=item.sortKeyword||v21QuoteKeyword_(item.name,item.code);item.duplicateKey=v21QuoteDuplicateKey_(item);});
  var duplicateCounts={};items.forEach(function(item){if(item.duplicateKey)duplicateCounts[item.duplicateKey]=(duplicateCounts[item.duplicateKey]||0)+1;});items.forEach(function(item){item.duplicateCount=duplicateCounts[item.duplicateKey]||1;});
  return items.sort(function(a,b){return v21Text_(a.sortKeyword).localeCompare(v21Text_(b.sortKeyword),'zh-Hant')||v21Text_(a.group).localeCompare(v21Text_(b.group),'zh-Hant')||v21Text_(a.category).localeCompare(v21Text_(b.category),'zh-Hant')||v21Text_(a.name).localeCompare(v21Text_(b.name),'zh-Hant')||v21Text_(a.code).localeCompare(v21Text_(b.code),'zh-Hant');});
}

function v21LoadQuoteCatalog_(includeArchived) {
  var raw=v21LoadQuoteCatalogRaw_(includeArchived),groups={};
  raw.forEach(function(item){var key=item.duplicateKey||('ID:'+item.id);if(!groups[key])groups[key]=[];groups[key].push(item);});
  return Object.keys(groups).map(function(key){
    var group=groups[key].slice().sort(function(a,b){
      var activeA=a.status==='封存'?0:1,activeB=b.status==='封存'?0:1;if(activeA!==activeB)return activeB-activeA;
      var currentA=a.custom?1:0,currentB=b.custom?1:0;if(currentA!==currentB)return currentB-currentA;
      var priceA=Number(a.price||0)>0?1:0,priceB=Number(b.price||0)>0?1:0;if(priceA!==priceB)return priceB-priceA;
      return v21Text_(b.updatedAt).localeCompare(v21Text_(a.updatedAt));
    });
    var canonical=group[0];canonical.duplicateCount=group.length;canonical.duplicateIds=group.slice(1).map(function(item){return item.id;});return canonical;
  }).filter(function(item){return includeArchived||item.status!=='封存';}).sort(function(a,b){return v21Text_(a.sortKeyword).localeCompare(v21Text_(b.sortKeyword),'zh-Hant')||v21Text_(a.name).localeCompare(v21Text_(b.name),'zh-Hant');});
}

function v21LoadQuoteItemOverrides_() {var rows=v21ReadCanonicalObjects_(PMO_V21.SHEETS.QUOTE_ITEMS,PMO_V21.HEADERS.QUOTE_ITEMS),result={};rows.forEach(function(row){var id=v21Text_(row['品項ID']);if(id)result[id]={id:id,sourceItemId:v21Text_(row['來源品項ID']),group:v21Text_(row['大分類']),category:v21Text_(row['分類']),code:v21Text_(row['品號']),name:v21Text_(row['品名規格']),unit:v21Text_(row['單位']),cost:v21Number_(row['成本單價']),price:v21Number_(row['建議報價單價']),supplier:v21Text_(row['供應商']),note:v21Text_(row['備註']),imageUrl:v21Text_(row['圖片連結']),status:v21Text_(row['狀態'])||'啟用',sortKeyword:v21Text_(row['排序關鍵字']),createdBy:v21Text_(row['建立者']),createdAt:v21Text_(row['建立時間']),updatedAt:v21Text_(row['更新時間'])};});return result;}
function v21ApplyQuoteOverride_(item,override) {['sourceItemId','group','category','code','name','unit','cost','price','supplier','note','imageUrl','status','sortKeyword','createdBy','createdAt','updatedAt'].forEach(function(key){if(override[key]!==undefined)item[key]=override[key];});item.custom=!item.sourceItemId||item.sourceItemId!==item.id;return item;}
function v21QuoteKeyword_(name,code) {var text=(v21Text_(name)+' '+v21Text_(code)).toLowerCase(),patterns=['車牌辨識','通關機','繳費機','驗票機','讀卡機','門禁控制器','電梯控制器','磁力鎖','陽極鎖','陰極鎖','對講機','攝影機','柵欄機','折臂機','出票機','交換器','伺服器','感應器','天線','rfid','ups','hub','led','電腦','螢幕'];for(var i=0;i<patterns.length;i+=1)if(text.indexOf(patterns[i])>=0)return patterns[i].toUpperCase();return text.replace(/[（）()\[\]{}_/\\-]/g,' ').replace(/\b\d+(?:\.\d+)?(?:mm|cm|m|v|a|w|p|port)?\b/gi,' ').replace(/\s+/g,' ').trim().slice(0,16)||'其他';}
function v21QuoteDuplicateKey_(item) {var normalize=function(value){return v21Text_(value).toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g,'');},code=normalize(item.code);return code?('CODE:'+code):('NAME:'+normalize(item.name)+'|'+normalize(item.unit));}

function saveQuoteCatalogItemV21(payload) {
  return v21Safe_('SAVE_QUOTE_ITEM',function(){
    payload=payload||{};
    var id=v21Text_(payload.id),existing=id?v21LoadQuoteCatalogRaw_(true).filter(function(item){return item.id===id;})[0]:null,name=v21Text_(payload.name);
    if(id&&!existing)throw new Error('找不到設備品項。');
    if(!name)throw new Error('設備名稱／規格不得空白。');
    var price=v21Number_(payload.price),cost=v21Number_(payload.cost);
    if(price<0||cost<0)throw new Error('價格不可小於 0。');
    var candidate={code:v21Text_(payload.code),name:name,unit:v21Text_(payload.unit)||'式'},key=v21QuoteDuplicateKey_(candidate),duplicate=v21LoadQuoteCatalogRaw_(false).filter(function(item){return item.id!==id&&v21QuoteDuplicateKey_(item)===key;})[0];
    if(!id&&duplicate)id=duplicate.id;
    return v21WithLock_(function(){
      var now=v21Now_();existing=existing||duplicate;id=id||v21Id_('EQ');
      var previousMedia=v21EquipmentMediaMap_()[id]||{},newImageUrl=v21Text_(payload.imageUrl),coverUrl=newImageUrl||previousMedia.imageUrl||'';
      v21UpsertObject_(PMO_V21.SHEETS.QUOTE_ITEMS,PMO_V21.HEADERS.QUOTE_ITEMS,'品項ID',{'品項ID':id,'來源品項ID':existing?(existing.sourceItemId||existing.id):'','大分類':v21Text_(payload.group),'分類':v21Text_(payload.category),'品號':candidate.code,'品名規格':name,'單位':candidate.unit,'成本單價':cost,'建議報價單價':price,'供應商':v21Text_(payload.supplier),'備註':v21Text_(payload.note),'圖片連結':coverUrl,'狀態':v21Text_(payload.status)||'啟用','排序關鍵字':v21Text_(payload.sortKeyword)||v21QuoteKeyword_(name,payload.code),'建立者':existing&&existing.createdBy?existing.createdBy:v21User_(),'建立時間':existing&&existing.createdAt?existing.createdAt:now,'更新時間':now});
      v21UpsertObject_(PMO_V21.SHEETS.EQUIPMENT_MEDIA,PMO_V21.HEADERS.EQUIPMENT_MEDIA,'品項ID',{'品項ID':id,'圖片連結':coverUrl,'設備說明':v21Text_(payload.note),'更新者':v21User_(),'更新時間':now});
      if(newImageUrl)v21RegisterEquipmentImage_(id,{url:newImageUrl,displayName:'設備圖片連結',originalName:'',mimeType:'image/external'});
      v21Audit_('SAVE_QUOTE_ITEM','報價設備',id,'成功',name+(duplicate?'（合併既有同設備）':''));
      return {id:id,name:name,status:v21Text_(payload.status)||'啟用',mergedExisting:!!duplicate};
    });
  });
}

function archiveQuoteCatalogItemV21(payload) {return v21Safe_('ARCHIVE_QUOTE_ITEM',function(){var id=v21Text_(payload&&payload.itemId),item=v21LoadQuoteCatalogRaw_(true).filter(function(row){return row.id===id;})[0];if(!item)throw new Error('找不到設備品項。');return v21WithLock_(function(){var now=v21Now_();v21UpsertObject_(PMO_V21.SHEETS.QUOTE_ITEMS,PMO_V21.HEADERS.QUOTE_ITEMS,'品項ID',{'品項ID':item.id,'來源品項ID':item.sourceItemId||'','大分類':item.group,'分類':item.category,'品號':item.code,'品名規格':item.name,'單位':item.unit,'成本單價':item.cost,'建議報價單價':item.price,'供應商':item.supplier,'備註':item.note,'圖片連結':item.imageUrl,'狀態':'封存','排序關鍵字':item.sortKeyword||v21QuoteKeyword_(item.name,item.code),'建立者':item.createdBy||v21User_(),'建立時間':item.createdAt||now,'更新時間':now});v21Audit_('ARCHIVE_QUOTE_ITEM','報價設備',id,'成功','安全封存，不影響歷史報價：'+item.name);return {id:id,status:'封存',recoverable:true};});});}

function v21EquipmentMediaMap_() {var sheet=v21GetSheet_(PMO_V21.SHEETS.EQUIPMENT_MEDIA,false),result={};if(sheet&&sheet.getLastRow()>1){var table=v21ReadTable_(PMO_V21.SHEETS.EQUIPMENT_MEDIA),map=v21HeaderMap_(table.headers);table.rows.forEach(function(row){var id=v21Text_(v21Pick_(row,map,['品項ID']));if(id)result[id]={imageUrl:v21Text_(v21Pick_(row,map,['圖片連結'])),description:v21Text_(v21Pick_(row,map,['設備說明'])),images:[]};});}v21LoadAttachments_().forEach(function(item){if(item.entityType!=='報價設備圖片'||!item.entityId)return;if(!result[item.entityId])result[item.entityId]={imageUrl:'',description:'',images:[]};result[item.entityId].images.push({id:item.id,url:item.url,displayName:item.displayName,originalName:item.originalName,mimeType:item.mimeType});});return result;}
function v21RegisterEquipmentImage_(itemId,image) {var url=v21Text_(image&&image.url);if(!/^https:\/\//i.test(url))return null;var id='ATT-'+v21Hash_('報價設備圖片|'+itemId+'|'+url),now=v21Now_();v21UpsertObject_(PMO_V21.SHEETS.ATTACHMENTS,PMO_V21.HEADERS.ATTACHMENTS,'附件ID',{'附件ID':id,'資料類型':'報價設備圖片','關聯ID':itemId,'專案ID':'','顯示名稱':v21Text_(image.displayName)||v21Text_(image.originalName)||'設備圖片','連結':url,'原始檔名':v21Text_(image.originalName),'MimeType':v21Text_(image.mimeType)||'image/*','建立者':v21User_(),'建立時間':now,'更新時間':now});return id;}
function saveEquipmentImageV21(payload) {return v21Safe_('SAVE_EQUIPMENT_IMAGE',function(){payload=payload||{};var id=v21Text_(payload.itemId),url=v21Text_(payload.imageUrl);if(!v21LoadQuoteCatalogRaw_(true).some(function(item){return item.id===id;}))throw new Error('找不到報價品項。');if(url&&!/^https:\/\//i.test(url))throw new Error('圖片連結必須使用 HTTPS。');return v21WithLock_(function(){var current=v21EquipmentImages_(id);if(url&&!current.some(function(item){return item.url===url;})&&current.length>=PMO_V21.MAX_EQUIPMENT_IMAGES)throw new Error('每個設備最多 '+PMO_V21.MAX_EQUIPMENT_IMAGES+' 張圖片。');v21UpsertObject_(PMO_V21.SHEETS.EQUIPMENT_MEDIA,PMO_V21.HEADERS.EQUIPMENT_MEDIA,'品項ID',{'品項ID':id,'圖片連結':url,'設備說明':v21Text_(payload.description),'更新者':v21User_(),'更新時間':v21Now_()});if(url)v21RegisterEquipmentImage_(id,{url:url,displayName:v21Text_(payload.displayName)||'設備圖片連結',mimeType:'image/external'});v21Audit_('SAVE_EQUIPMENT_IMAGE','設備圖片',id,'成功',url);return {itemId:id,imageUrl:url,images:v21EquipmentImages_(id)};});});}
function v21EquipmentImages_(itemId) {return v21AttachmentsForEntity_('報價設備圖片',itemId,'');}
function uploadEquipmentImageV21(payload) {return v21Safe_('UPLOAD_EQUIPMENT_IMAGE',function(){payload=payload||{};var dataUrl=v21Text_(payload.dataUrl),match=dataUrl.match(/^data:(image\/[^;]+);base64,(.+)$/);if(!match)throw new Error('只接受圖片檔案。');var bytes=Utilities.base64Decode(match[2]);if(bytes.length>PMO_V21.MAX_EQUIPMENT_IMAGE_BYTES)throw new Error('單張圖片不可超過 10 MB。');var itemId=v21Text_(payload.itemId),item=v21LoadQuoteCatalogRaw_(true).filter(function(row){return row.id===itemId;})[0];if(!item)throw new Error('找不到報價品項。');if(v21EquipmentImages_(itemId).length>=PMO_V21.MAX_EQUIPMENT_IMAGES)throw new Error('每個設備最多 '+PMO_V21.MAX_EQUIPMENT_IMAGES+' 張圖片。');var folder=v21EquipmentMediaFolder_(),filename=(item.code||item.id)+'_'+v21Text_(payload.filename).replace(/[\\/:*?"<>|]/g,'_'),file=folder.createFile(Utilities.newBlob(bytes,match[1],filename));return v21WithLock_(function(){var id=v21RegisterEquipmentImage_(itemId,{url:file.getUrl(),displayName:v21Text_(payload.displayName)||file.getName(),originalName:v21Text_(payload.filename)||file.getName(),mimeType:file.getMimeType()});var media=v21EquipmentMediaMap_()[itemId]||{},setCover=payload.setAsCover===true||v21Text_(payload.setAsCover)==='true'||!media.imageUrl;if(setCover)v21UpsertObject_(PMO_V21.SHEETS.EQUIPMENT_MEDIA,PMO_V21.HEADERS.EQUIPMENT_MEDIA,'品項ID',{'品項ID':itemId,'圖片連結':file.getUrl(),'設備說明':v21Text_(payload.description)||item.note,'更新者':v21User_(),'更新時間':v21Now_()});v21Audit_('UPLOAD_EQUIPMENT_IMAGE','設備圖片',id,'成功',file.getName()+' '+bytes.length+' bytes'+(setCover?'；設為封面':''));return {itemId:itemId,imageId:id,imageUrl:file.getUrl(),fileId:file.getId(),size:bytes.length,name:file.getName(),isCover:setCover};});});}
function deleteEquipmentImageV21(payload) {return v21Safe_('DELETE_EQUIPMENT_IMAGE',function(){payload=payload||{};var itemId=v21Text_(payload.itemId),imageId=v21Text_(payload.imageId),image=v21EquipmentImages_(itemId).filter(function(row){return row.id===imageId;})[0];if(!image)throw new Error('找不到要刪除的設備圖片。');return v21WithLock_(function(){var driveId=v21ExtractDriveId_(image.url),trashed=false;if(driveId){try{DriveApp.getFileById(driveId).setTrashed(true);trashed=true;}catch(ignored){}}v21DeleteRowByKey_(PMO_V21.SHEETS.ATTACHMENTS,'附件ID',imageId);var remaining=v21EquipmentImages_(itemId),next=remaining.length?remaining[0].url:'';v21UpsertObject_(PMO_V21.SHEETS.EQUIPMENT_MEDIA,PMO_V21.HEADERS.EQUIPMENT_MEDIA,'品項ID',{'品項ID':itemId,'圖片連結':next,'更新者':v21User_(),'更新時間':v21Now_()});v21Audit_('DELETE_EQUIPMENT_IMAGE','設備圖片',imageId,'成功',(trashed?'檔案移至垃圾桶；':'移除外部連結；')+image.url);return {itemId:itemId,imageId:imageId,trashed:trashed,remaining:remaining.length,recoverable:trashed};});});}
function v21EquipmentMediaFolder_() {var properties=PropertiesService.getScriptProperties(),id=properties.getProperty(PMO_V21.EQUIPMENT_MEDIA_FOLDER_PROPERTY);if(id)return DriveApp.getFolderById(id);var folder=v21FindOrCreateChildFolder_(v21ProjectRoot_(),'V21_設備圖片');properties.setProperty(PMO_V21.EQUIPMENT_MEDIA_FOLDER_PROPERTY,folder.getId());return folder;}

function getQuoteDetailV21(payload) {return v21Safe_('GET_QUOTE_DETAIL',function(){var id=v21Text_(payload&&payload.quoteId),master=v21LoadQuoteMasterById_(id);if(!master)throw new Error('找不到可編輯的 V21 報價單。');return {master:master,lines:v21LoadQuoteLines_(id),file:v21LatestQuoteFile_(id)};});}

function deleteQuoteDraftV21(payload) {return v21Safe_('DELETE_QUOTE_DRAFT',function(){payload=payload||{};var id=v21Text_(payload.quoteId),confirmId=v21Text_(payload.confirmQuoteId),master=v21LoadQuoteMasterById_(id);if(!master)throw new Error('找不到草稿報價單。');if(master.status!=='草稿')throw new Error('只有草稿報價單可以刪除。');if(confirmId!==id)throw new Error('確認用報價 ID 不一致，未刪除。');return v21WithLock_(function(){var files=v21ReadCanonicalObjects_(PMO_V21.SHEETS.QUOTE_FILES,PMO_V21.HEADERS.QUOTE_FILES).filter(function(row){return v21Text_(row['報價ID'])===id;}),trashed=0;files.forEach(function(row){['試算表連結','PDF連結'].forEach(function(header){var fileId=v21ExtractDriveId_(row[header]);if(!fileId)return;try{DriveApp.getFileById(fileId).setTrashed(true);trashed+=1;}catch(ignored){}});});v21DeleteRowsWhere_(PMO_V21.SHEETS.QUOTE_FILES,function(row){return v21Text_(row['報價ID'])===id;});v21UpsertObject_(PMO_V21.SHEETS.QUOTE_MASTER,PMO_V21.HEADERS.QUOTE_MASTER,'報價ID',{'報價ID':id,'狀態':'已刪除','更新時間':v21Now_()});v21Audit_('DELETE_QUOTE_DRAFT','報價單',id,'成功','產出檔案移至垃圾桶 '+trashed+' 個；明細與稽核資料保留');return {id:id,status:'已刪除',trashedFiles:trashed,recoverableFiles:trashed>0};});});}

function v21DeleteRowsWhere_(sheetName,predicate) {var sheet=v21GetSheet_(sheetName,false);if(!sheet||sheet.getLastRow()<=1)return 0;var headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0].map(v21Text_),values=sheet.getRange(2,1,sheet.getLastRow()-1,sheet.getLastColumn()).getValues(),deleted=0;for(var i=values.length-1;i>=0;i-=1){var object={};headers.forEach(function(header,index){object[header]=values[i][index];});if(predicate(object)){sheet.deleteRow(i+2);deleted+=1;}}return deleted;}

function saveQuoteDraftV21(payload) {return v21Safe_('SAVE_QUOTE',function(){payload=payload||{};var projectId=v21Text_(payload.projectId),project=v21LoadProjects_().filter(function(item){return item.id===projectId;})[0];if(!project||project.status==='封存')throw new Error('請選擇有效且未封存的專案。');var requested=Array.isArray(payload.lines)?payload.lines:[];if(!requested.length)throw new Error('請至少選擇一個設備／報價品項。');if(requested.length>100)throw new Error('單張報價最多 100 個品項。');var catalog=v21LoadQuoteCatalogRaw_(true),byId={};catalog.forEach(function(item){byId[item.id]=item;});var normalized=requested.map(function(line,index){var item=byId[v21Text_(line.itemId)];if(!item)throw new Error('第 '+(index+1)+' 項不存在。');var quantity=v21Number_(line.quantity),price=line.price===''||line.price===undefined?item.price:v21Number_(line.price);if(quantity<=0||price<0)throw new Error('第 '+(index+1)+' 項數量或單價不正確。');return {item:item,quantity:quantity,price:price,amount:Math.round(quantity*price),note:v21Text_(line.note)};});
    var saved=v21WithLock_(function(){var existingId=v21Text_(payload.id),existing=existingId?v21LoadQuoteMasterById_(existingId):null;if(existingId&&!existing)throw new Error('找不到要編輯的報價單。');var quoteId=existing?existing.id:v21Id_('QUOTE'),now=v21Now_(),subtotal=normalized.reduce(function(sum,line){return sum+line.amount;},0),taxRate=payload.taxRate===''||payload.taxRate===undefined?5:v21Number_(payload.taxRate),tax=Math.round(subtotal*taxRate/100),total=subtotal+tax,version=existing?v21NextQuoteVersion_(existing.version):'V1',quoteNo=existing?existing.quoteNo:(v21Text_(payload.quoteNo)||('Q-'+Utilities.formatDate(new Date(),PMO_V21.TIME_ZONE,'yyyyMMdd-HHmmss'))),createdAt=existing&&existing.createdAt?existing.createdAt:now;
      v21UpsertObject_(PMO_V21.SHEETS.QUOTE_MASTER,PMO_V21.HEADERS.QUOTE_MASTER,'報價ID',{'報價ID':quoteId,'報價單號':quoteNo,'版本':version,'狀態':'草稿','報價日期':v21Date_(payload.date)||v21Today_(),'專案ID':project.id,'專案名稱':project.name,'客戶名稱':v21Text_(payload.customer)||project.customer,'未稅小計':subtotal,'稅率':taxRate,'營業稅':tax,'含稅總額':total,'備註':v21Text_(payload.note),'建立者':existing&&existing.createdBy?existing.createdBy:v21User_(),'建立時間':createdAt,'更新時間':now});var lineObjects=normalized.map(function(line,index){return {'明細ID':quoteId+'-'+('000'+(index+1)).slice(-3),'報價ID':quoteId,'項次':index+1,'品項ID':line.item.id,'大分類':line.item.group,'分類':line.item.category,'品號':line.item.code,'品名規格':line.item.name,'單位':line.item.unit,'數量':line.quantity,'單價':line.price,'未稅金額':line.amount,'備註':line.note,'圖片連結':line.item.imageUrl};});v21ReplaceQuoteLines_(quoteId,lineObjects);v21Audit_('SAVE_QUOTE','報價單',quoteId,'成功',quoteNo+' '+version+' '+total);return {id:quoteId,quoteNo:quoteNo,version:version,date:v21Date_(payload.date)||v21Today_(),project:project,customer:v21Text_(payload.customer)||project.customer,subtotal:subtotal,taxRate:taxRate,tax:tax,total:total,note:v21Text_(payload.note),lines:lineObjects,sourceQuoteId:v21Text_(payload.sourceQuoteId)};});
    try{saved.file=v21GenerateQuoteFiles_(saved);}catch(error){saved.exportError=error&&error.message?error.message:String(error);v21Audit_('EXPORT_QUOTE','報價檔案',saved.id,'失敗',saved.exportError);}return saved;
  });}

function generateQuoteFilesV21(payload) {return v21Safe_('GENERATE_QUOTE_FILES',function(){var detail=getQuoteDetailV21({quoteId:v21Text_(payload&&payload.quoteId)});if(!detail.ok)throw new Error(detail.message);var master=detail.data.master,project=v21LoadProjects_().filter(function(item){return item.id===master.projectId;})[0];if(!project)throw new Error('報價單專案不存在。');return v21GenerateQuoteFiles_({id:master.id,quoteNo:master.quoteNo,version:master.version,date:master.date,project:project,customer:master.customer,subtotal:master.subtotal,taxRate:master.taxRate,tax:master.tax,total:master.total,note:master.note,lines:detail.data.lines.map(v21QuoteLineObject_),sourceQuoteId:''});});}

function v21GenerateQuoteFiles_(quote) {var folder=v21QuoteOutputFolder_(quote.project),safeName=[quote.quoteNo,quote.version,quote.project.name,quote.date].filter(Boolean).join('_').replace(/[\\/:*?"<>|]/g,'_'),book=SpreadsheetApp.create(safeName),sheet=book.getSheets()[0];sheet.setName('報價單');sheet.getRange('A1:H1').merge().setValue('PSS 專案設備報價單').setFontSize(18).setFontWeight('bold').setHorizontalAlignment('center').setBackground('#16324f').setFontColor('#ffffff');sheet.getRange('A2:H2').merge().setValue('報價單號：'+quote.quoteNo+'　版本：'+quote.version+'　日期：'+quote.date).setHorizontalAlignment('center');sheet.getRange('A3:D3').merge().setValue('專案：'+quote.project.name+'（'+quote.project.id+'）');sheet.getRange('E3:H3').merge().setValue('客戶：'+(quote.customer||''));var headers=['項次','品號','品名／規格','單位','數量','單價','未稅金額','備註'],start=5;sheet.getRange(start,1,1,headers.length).setValues([headers]).setFontWeight('bold').setBackground('#dbeafe');var values=quote.lines.map(function(line){return [line['項次'],line['品號'],line['品名規格'],line['單位'],line['數量'],line['單價'],line['未稅金額'],line['備註']];});if(values.length)sheet.getRange(start+1,1,values.length,headers.length).setValues(values);var totalRow=start+1+values.length;sheet.getRange(totalRow,6,3,2).setValues([['未稅小計',quote.subtotal],['營業稅 '+quote.taxRate+'%',quote.tax],['含稅總額',quote.total]]).setFontWeight('bold');sheet.getRange(totalRow+3,1,1,8).merge().setValue('備註：'+(quote.note||''));sheet.getRange(totalRow+4,1,1,8).merge().setValue('本報價資料由 PSS AI-PMO 產出；實際內容仍以核准版本為準。');if(values.length)sheet.getRange(start+1,5,values.length,3).setNumberFormat('#,##0.##');sheet.setColumnWidth(1,50);sheet.setColumnWidth(2,110);sheet.setColumnWidth(3,300);sheet.setColumnWidth(4,60);sheet.setColumnWidth(5,70);sheet.setColumnWidth(6,100);sheet.setColumnWidth(7,110);sheet.setColumnWidth(8,220);sheet.setFrozenRows(start);SpreadsheetApp.flush();var file=DriveApp.getFileById(book.getId());file.moveTo(folder);var pdf=folder.createFile(file.getAs(MimeType.PDF).setName(safeName+'.pdf')),recordId='QF-'+v21Hash_(quote.id+'|'+quote.version+'|'+file.getId()),now=v21Now_();v21WithLock_(function(){v21UpsertObject_(PMO_V21.SHEETS.QUOTE_FILES,PMO_V21.HEADERS.QUOTE_FILES,'檔案ID',{'檔案ID':recordId,'報價ID':quote.id,'版本':quote.version,'專案ID':quote.project.id,'試算表連結':file.getUrl(),'PDF連結':pdf.getUrl(),'資料夾連結':folder.getUrl(),'來源報價ID':quote.sourceQuoteId||'','建立者':v21User_(),'建立時間':now});});v21Audit_('EXPORT_QUOTE','報價檔案',quote.id,'成功',quote.version+' '+folder.getUrl());return {spreadsheetUrl:file.getUrl(),pdfUrl:pdf.getUrl(),folderUrl:folder.getUrl(),version:quote.version};}
function v21QuoteOutputFolder_(project) {if(!project||!project.folderUrl)throw new Error('此專案尚未設定雲端資料夾，無法產出報價檔案。');var root=DriveApp.getFolderById(v21ExtractDriveId_(project.folderUrl)),contracts=v21FindOrCreateChildFolder_(root,'01_合約訂單銷貨驗收文件');return v21FindOrCreateChildFolder_(contracts,'報價單');}

function v21ReplaceQuoteLines_(quoteId,objects) {var sheet=v21EnsureSheet_(PMO_V21.SHEETS.QUOTE_LINES,PMO_V21.HEADERS.QUOTE_LINES),values=sheet.getLastRow()>1?sheet.getRange(2,1,sheet.getLastRow()-1,PMO_V21.HEADERS.QUOTE_LINES.length).getValues():[],quoteIndex=PMO_V21.HEADERS.QUOTE_LINES.indexOf('報價ID'),keep=values.filter(function(row){return v21Text_(row[quoteIndex])!==quoteId;}),additions=objects.map(function(object){return PMO_V21.HEADERS.QUOTE_LINES.map(function(header){return object[header]===undefined?'':object[header];});}),all=keep.concat(additions);if(sheet.getLastRow()>1)sheet.getRange(2,1,sheet.getLastRow()-1,PMO_V21.HEADERS.QUOTE_LINES.length).clearContent();if(all.length)sheet.getRange(2,1,all.length,PMO_V21.HEADERS.QUOTE_LINES.length).setValues(all);}
function v21QuoteLineObject_(line) {return {'明細ID':line.id,'報價ID':line.quoteId,'項次':line.index,'品項ID':line.itemId,'大分類':line.group,'分類':line.category,'品號':line.code,'品名規格':line.name,'單位':line.unit,'數量':line.quantity,'單價':line.price,'未稅金額':line.amount,'備註':line.note,'圖片連結':line.imageUrl};}
function v21LoadQuoteMasterById_(id) {var rows=v21ReadCanonicalObjects_(PMO_V21.SHEETS.QUOTE_MASTER,PMO_V21.HEADERS.QUOTE_MASTER),row=rows.filter(function(item){return v21Text_(item['報價ID'])===id;})[0];return row?{id:v21Text_(row['報價ID']),quoteNo:v21Text_(row['報價單號']),version:v21Text_(row['版本'])||'V1',status:v21Text_(row['狀態']),date:v21Date_(row['報價日期']),projectId:v21Text_(row['專案ID']),projectName:v21Text_(row['專案名稱']),customer:v21Text_(row['客戶名稱']),subtotal:v21Number_(row['未稅小計']),taxRate:v21Number_(row['稅率']),tax:v21Number_(row['營業稅']),total:v21Number_(row['含稅總額']),note:v21Text_(row['備註']),createdBy:v21Text_(row['建立者']),createdAt:v21Text_(row['建立時間']),updatedAt:v21Text_(row['更新時間'])}:null;}
function v21LoadQuoteLines_(quoteId) {return v21ReadCanonicalObjects_(PMO_V21.SHEETS.QUOTE_LINES,PMO_V21.HEADERS.QUOTE_LINES).filter(function(row){return v21Text_(row['報價ID'])===quoteId;}).sort(function(a,b){return v21Number_(a['項次'])-v21Number_(b['項次']);}).map(function(row){return {id:v21Text_(row['明細ID']),quoteId:quoteId,index:v21Number_(row['項次']),itemId:v21Text_(row['品項ID']),group:v21Text_(row['大分類']),category:v21Text_(row['分類']),code:v21Text_(row['品號']),name:v21Text_(row['品名規格']),unit:v21Text_(row['單位']),quantity:v21Number_(row['數量']),price:v21Number_(row['單價']),amount:v21Number_(row['未稅金額']),note:v21Text_(row['備註']),imageUrl:v21Text_(row['圖片連結'])};});}
function v21NextQuoteVersion_(version) {var match=v21Text_(version).match(/(\d+)/);return 'V'+((match?Number(match[1]):0)+1);}
function v21QuoteFilesMap_() {var rows=v21ReadCanonicalObjects_(PMO_V21.SHEETS.QUOTE_FILES,PMO_V21.HEADERS.QUOTE_FILES),map={};rows.sort(function(a,b){return v21Text_(b['建立時間']).localeCompare(v21Text_(a['建立時間']));}).forEach(function(row){var id=v21Text_(row['報價ID']);if(id&&!map[id])map[id]={spreadsheetUrl:v21Text_(row['試算表連結']),pdfUrl:v21Text_(row['PDF連結']),folderUrl:v21Text_(row['資料夾連結']),version:v21Text_(row['版本']),createdAt:v21Text_(row['建立時間'])};});return map;}
function v21LatestQuoteFile_(quoteId) {return v21QuoteFilesMap_()[quoteId]||null;}
function v21LoadRecentQuotes_() {var result=[],files=v21QuoteFilesMap_();[[PMO_V21.SHEETS.QUOTE_MASTER,false],[PMO_V21.SHEETS.LEGACY_QUOTE_MASTER,true]].forEach(function(spec){var sheet=spec[1]?v21SourceDb_().getSheetByName(spec[0]):v21GetSheet_(spec[0],false);if(!sheet||sheet.getLastRow()<=1)return;var table=v21ReadTable_(spec[0],spec[1]?v21SourceDb_():v21Db_()),map=v21HeaderMap_(table.headers);table.rows.forEach(function(row){var id=v21Text_(v21Pick_(row,map,['報價ID'])),status=v21Text_(v21Pick_(row,map,['狀態']));if(!id||/已刪除|作廢|取消/.test(status))return;var file=files[id]||{};result.push({id:id,quoteNo:v21Text_(v21Pick_(row,map,['報價單號'])),version:v21Text_(v21Pick_(row,map,['版本']))||'V1',projectId:v21Text_(v21Pick_(row,map,['專案ID','場地代號'])),projectName:v21Text_(v21Pick_(row,map,['專案名稱'])),customer:v21Text_(v21Pick_(row,map,['客戶名稱'])),status:status,date:v21Date_(v21Pick_(row,map,['報價日期'])),total:v21Number_(v21Pick_(row,map,['含稅總額'])),updatedAt:v21Text_(v21Pick_(row,map,['更新時間'])),editable:!spec[1],spreadsheetUrl:file.spreadsheetUrl||'',pdfUrl:file.pdfUrl||'',folderUrl:file.folderUrl||''});});});var seen={};return result.filter(function(item){if(seen[item.id])return false;seen[item.id]=true;return true;}).sort(function(a,b){return v21Text_(b.updatedAt||b.date).localeCompare(v21Text_(a.updatedAt||a.date));});}
