/** Apps Script editor self-tests. No sheet writes. */
function runV21SelfTests() {
  var tests = [];
  function assert(name, condition) { tests.push({name:name,passed:!!condition}); if(!condition) throw new Error('Self-test failed: '+name); }
  var headers=['場地代號','專案名稱','場地代號','狀態'];
  var map=v21HeaderMap_(headers);
  assert('重複欄名索引',map['場地代號'].length===2);
  assert('重複欄名取最後非空值',v21Pick_(['OLD','測試案','NEW','進行中'],map,['場地代號'])==='NEW');
  assert('待安排正規化為事項',v21NormalizeStatus_('待安排')==='事項');
  assert('舊進行中正規化為目前處理',v21NormalizeStatus_('進行中')==='目前處理');
  assert('舊取消正規化為無須追蹤',v21NormalizeStatus_('取消')==='無須追蹤');
  assert('空白進度為 0',v21Number_('')===0);
  assert('日期正規化',v21Date_('2026/8/3')==='2026-08-03');
  var drawing=v21DrawingState_({id:'P1',drawingStatus:''},[{projectId:'P1',title:'圖面已送審',status:'進行中',updatedAt:'2026-08-01',sourceSheet:'任務派工'}],[],[],{});
  assert('圖面送審推導',drawing.status==='送審中');
  assert('圖片分類',v21FileKind_('現場照片.JPG','image/jpeg')==='image');
  assert('CAD 分類',v21FileKind_('施工圖.dwg','application/octet-stream')==='cad');
  assert('文件分類',v21FileKind_('報價表.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')==='document');
  assert('狀態只提供建議',v21SuggestProjectStatus_({progress:30,status:'施作中'},[{status:'事項'}])==='待追蹤');
  assert('診斷頁 HTML 跳脫',v21EscapeHtml_('<錯誤>')==='&lt;錯誤&gt;');
  assert('週四會議有效日期',v21IsIsoDay_('2026-08-13')===true);
  assert('週四會議拒絕空白日期',v21IsIsoDay_('')===false);
  var meeting=v21NormalizeMeetingSnapshot_({items:[{group:'未知分類',projectName:null,title:'測試事項'}],groups:null,byPerson:null,persisted:false});
  assert('週四會議快照格式修復',meeting.groups['本週未完成'].length===1&&meeting.counts['本週未完成']===1&&typeof meeting.byPerson==='object');
  assert('會議完成狀態不重開',v21MeetingRecordTrackingStatus_('已完成')==='完成');
  assert('會議待確認轉事項',v21MeetingRecordTrackingStatus_('待業主確認')==='事項');
  assert('會議請款轉目前處理',v21MeetingRecordTrackingStatus_('已驗收請款進行中')==='目前處理');
  assert('會議多期限取最終日',v21MeetingLastDate_('2026-08-14 / 2026-08-21')==='2026-08-21');
  assert('會議主檔編號固定',v21MeetingMasterId_('2026-08-13')==='MTG-20260813');
  assert('會議決議與後續合併',v21MeetingDecisionText_('已確認','下週複查')==='已確認\n後續：下週複查');
  var signerNames=v21MeetingSignerNames_({meetingRecord:{participants:'簡宏義、黃侯諴、陳彥均、張亭媛'}});
  assert('會議簽名欄不重複',signerNames.length===4&&signerNames[0]==='簡宏義');
  assert('8月13日會議紀錄共38筆',v21MeetingRecord20260813Data_().length===38);
  assert('週四日期位移接受文字日期',v21CoerceIsoDate_('2026-08-10').getUTCDate()===10);
  assert('繪圖申請已送審資料共221筆',v21DrawingProgressSource20260814_().length===221);
  var drawingPlan=v21BuildDrawingImportPlan_([{id:'PSS_IC0608',name:'國泰小檜溪大樓'}],[{r:40,p:'桃園小檜溪',d:'2025-04-11',n:'竣工圖',u:'https://drive.google.com/test'}]);
  assert('繪圖專案別名唯一配對',drawingPlan.recordsToWrite===1&&drawingPlan.records[0].projectId==='PSS_IC0608');
  var drawingMap=v21BuildCanonicalDrawingMap_([{id:'D0',projectId:'P1',status:'圖面完成（審查未確認）',submittedAt:'2026-06-22',updatedAt:'2026-08-14',attachment:'',sourceSheet:'任務派工',title:'推導圖面',review:'由最新紀錄推導'},{id:'D1',projectId:'P1',status:'完成',submittedAt:'2025-01-01',updatedAt:'2026-08-14',attachment:'https://drive.google.com/old',sourceSheet:'繪圖申請進度表',title:'舊圖',review:'完成'},{id:'D2',projectId:'P1',status:'完成',submittedAt:'2025-02-01',updatedAt:'2026-08-14',attachment:'https://drive.google.com/new',sourceSheet:'繪圖申請進度表',title:'新圖',review:'完成'}]);
  assert('圖面主檔依送審日期取最新連結',drawingMap.P1.title==='新圖'&&drawingMap.P1.attachment==='https://drive.google.com/new');
  assert('多附件主連結取第一筆有效連結',v21PrimaryAttachmentUrl_([{url:'https://drive.google.com/first'},{url:'https://drive.google.com/second'}],'')==='https://drive.google.com/first');
  assert('報價設備關鍵字歸類',v21QuoteKeyword_('四門門禁控制器 AC-400','AC400')==='門禁控制器');
  assert('報價設備同品號判斷重複',v21QuoteDuplicateKey_({code:' AC-400 ',name:'A',unit:'式'})===v21QuoteDuplicateKey_({code:'AC400',name:'B',unit:'台'}));
  assert('報價版本遞增',v21NextQuoteVersion_('V9')==='V10');
  assert('一般附件單檔上限提高至10MB',PMO_V21.MAX_UPLOAD_BYTES===10*1024*1024);
  assert('一般附件一次最多20個',PMO_V21.MAX_ATTACHMENT_FILES===20);
  assert('設備圖片每項最多12張',PMO_V21.MAX_EQUIPMENT_IMAGES===12&&PMO_V21.MAX_EQUIPMENT_IMAGE_BYTES===10*1024*1024);
  var legacyQuoteRows=v21LegacyQuoteRows_(),legacyKeys={};legacyQuoteRows.forEach(function(row){legacyKeys[v21QuoteDuplicateKey_(row)]=true;});
  assert('兩份舊報價抽取70筆案例',legacyQuoteRows.length===70);
  assert('舊報價去重後34項設備',Object.keys(legacyKeys).length===34);
  var importRow=v21NormalizeQuoteImportRow_({'品名規格':'測試設備','單位':'台','建議報價單價':'1,200','案例日期':'2026/8/14','匯入批次':'TEST'},0);
  assert('設備匯入欄位標準化',importRow.name==='測試設備'&&importRow.unit==='台'&&importRow.price===1200&&importRow.sourceDate==='2026-08-14');
  assert('工作關聯資料表已定義',PMO_V21.HEADERS.WORK_RELATIONS.indexOf('關聯工作ID')>=0&&PMO_V21.HEADERS.WORK_RELATIONS.indexOf('關聯專案ID')>=0);
  assert('工作狀態含軟刪除',PMO_V21.WORK_STATUSES.join('|')==='事項|目前處理|無須追蹤|完成|已刪除');
  assert('無須追蹤與完成與已刪除不列目前工作',PMO_V21.ACTIVE_STATUSES.indexOf('無須追蹤')<0&&PMO_V21.ACTIVE_STATUSES.indexOf('完成')<0&&PMO_V21.ACTIVE_STATUSES.indexOf('已刪除')<0);
  assert('已刪除狀態正規化',v21NormalizeStatus_('刪除')==='已刪除');
  assert('統整版版本號',PMO_V21.VERSION==='23.0.0');
  assert('部門專案管理試算表已設定',PMO_V21.PROGRESS_DATABASE_ID==='1Oh2pnlZwusM7E-CKMr-eYYYOToTzHtJge_2yiqEypcM');
  assert('系統類型包含批價機',V21_SYSTEM_TYPES.indexOf('批價機系統')>=0);
  assert('設備下載連結轉換',v224EquipmentDownloadUrl_('https://drive.google.com/file/d/12345678901234567890/view').indexOf('export=download')>=0);
  return {ok:true,version:PMO_V21.VERSION,tests:tests};
}
