/** Embedded, read-only export of submitted rows from PSS停管業務部PM管理.xlsx / 繪圖申請進度表. */
var V21_DRAWING_PROGRESS_20260814 = Object.freeze([
  {"r":2,"p":"國泰松江/國泰信義充電樁線路架構圖","d":"2025-04-24","n":"松江及信義充電樁線路架構圖 -繪製CAD檔","u":"https://drive.google.com/drive/folders/1277SF_9PfEogMnepHCySehX39niBs1Zc?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":3,"p":"525巷平面圖","d":"2025-04-25","n":"525巷平面圖\n/繪製 - 525巷平面位置圖 + 停管設備","u":"https://drive.google.com/file/d/1SHKbMLgmd7LwuR1YBHUH14msymZV1ncc/view?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":5,"p":"土城","d":"2025-04-23","n":"土城\n/1F~B4 停車設備規劃","u":"https://drive.google.com/drive/folders/1ex8ce5m0T5Fpr3Jyq7XXUo1Vf_oyJ0l2?usp=drive_link","a":"吳哲帆","w":"簡宏義"},
  {"r":6,"p":"土城金城路","d":"2025-03-11","n":"土城金城路\n/描圖竣工圖繪製 - 機車入出口停車場 \n方案一 , 方案二","u":"https://drive.google.com/drive/folders/1L0q8mI7CouSg3IQkQtkfPW0Hrlxr6yY1?usp=drive_link","a":"李銘華","w":"簡宏義"},
  {"r":7,"p":"中華工程 雲宇宙","d":"2025-02-26","n":"最新 -中工雲宇宙的竣工圖\n/把原設計規劃停管設備平面圖B1~B5 層全部移植到新的竣工圖","u":"","a":"高祥林","w":"簡宏義"},
  {"r":8,"p":"中華工程 雲宇宙","d":"2025-03-24","n":"中華工程 雲宇宙\n/整理 - B1~B2 車位在席圖面給現場水電","u":"","a":"高祥林","w":"簡宏義"},
  {"r":9,"p":"中華工程 雲宇宙","d":"2025-04-02","n":"中華工程 雲宇宙 - 水電B1線槽套圖","u":"","a":"高祥林","w":"簡宏義"},
  {"r":10,"p":"中華工程 雲宇宙","d":"2025-04-16","n":"中華工程 雲宇宙\n/修改-1樓平面 - 甲區汽車區車道設備\n/圖框 - 1F ~ B5層圖框套圖","u":"https://drive.google.com/drive/folders/1oi4vAGzSD1pdkQ_YfYRG5R-9DuO3J3bI?usp=drive_link","a":"高祥林","w":"簡宏義"},
  {"r":11,"p":"內湖矽塔中心","d":"2025-03-21","n":"內湖矽塔中心\n/繪製-汽機車共道\n/入出口設備基座","u":"https://drive.google.com/drive/folders/124XYe7HJQugY9wlZGHkgLqd2-YkKvRb0?usp=drive_link","a":"吳哲帆","w":"簡宏義"},
  {"r":13,"p":"台南置地","d":"2025-01-16","n":"台南置地\n/繪製 - B5 層車位在席鏡頭","u":"","a":"李銘華","w":"簡宏義"},
  {"r":14,"p":"台南置地","d":"2025-01-16","n":"台南置\n/繪製 - 6F行動辨公室-門禁+監視\n/繪製 - B5 , B4層車位在席鏡頭","u":"https://drive.google.com/drive/folders/17bUblF6BilEiF3Eri5zS8uhJrAvX7uPK?usp=drive_link","a":"李銘華","w":"簡宏義"},
  {"r":15,"p":"台南置地","d":"2025-01-20","n":"台南置\n/繪製 - B4 , B3層車位在席鏡頭\n/繪製 - 1F , B1,B2層停管設備 + \n汽車(B2)+機車(B1)入出口設備基座+B4汽車入口設備基座","u":"","a":"李銘華","w":"簡宏義"},
  {"r":16,"p":"台南置地","d":"2025-02-05","n":"修改 - 台南置地\n/1F -汽車入出口基座移置1F\n/B1-增加APS 及管理室 \n/刪除B5層車位在席鏡頭","u":"","a":"李銘華","w":"簡宏義"},
  {"r":17,"p":"台南置地","d":"2025-02-05","n":"修改 - 台南置地\n/1F -汽車入出口基座移置1F\n/B1-增加APS 及管理室 \n/刪除B5層車位在席鏡頭\n台南置地\n/6F - 行動辦公區 - 門禁系統估算線材長度","u":"https://drive.google.com/drive/folders/1cU8ZLrMXqI1UhBcwaND1pBKkQ6SIYwlu?usp=drive_link","a":"李銘華","w":"簡宏義"},
  {"r":18,"p":"台南置地","d":"2025-02-08","n":"修改 - 台南置地\n/6F - 行動辦公區 - 監視攝影機位置 \n/門禁讀頭 - 增加一顆","u":"","a":"李銘華","w":"簡宏義"},
  {"r":19,"p":"台南置地","d":"2025-02-10","n":"( 依據2/9 提供業主簡報檔 ) 修改 - 台南置地\n/6F - 行動辦公區 - 監視攝影機 -增加10支位置 \n/門禁讀頭 - 有刪除有增加","u":"","a":"李銘華","w":"簡宏義"},
  {"r":20,"p":"台南置地","d":"2025-02-13","n":"修改 - 台南置地 ( 視訊會議提供的6F簡報檔)\n/6F - 行動辦公區 - 監視攝影機\n增加門禁設備 及 CCTV監視攝影機位置","u":"","a":"李銘華","w":"簡宏義"},
  {"r":21,"p":"台南置地","d":"2025-02-14","n":"修改 - 台南置地\n/6F - 行動辦公區 - 監視攝影機位置 \n/圖面增加2支半球形攝影機","u":"","a":"李銘華","w":"簡宏義"},
  {"r":22,"p":"台南置地","d":"2025-05-02","n":"台南置地\n/修改- 6 F 行動辨公室-三處機房機櫃移位\n/門禁系統點位配合修改管路路徑\n/監控攝影機點位配合修改管路路徑","u":"","a":"Tearo Lin","w":"簡宏義"},
  {"r":23,"p":"巨城購物中心","d":"2025-04-17","n":"巨城購物中心\n/B3 B4層 - 車位在席鏡頭編輯各鏡頭編號及收容箱編號","u":"","a":"高崇仁","w":"簡宏義"},
  {"r":24,"p":"田心段","d":"2025-03-21","n":"田心段\n/繪製 - 1F 通關機 + 門禁設備\n/1F ~ 19 F + B1 ~ B4 層門禁設備","u":"","a":"李銘華","w":"簡宏義"},
  {"r":25,"p":"田心段","d":"2025-03-26","n":"田心段 - 門禁系統\n/繪製 - 2F 門禁系統架構圖","u":"","a":"李銘華","w":"簡宏義"},
  {"r":26,"p":"石頭段","d":"2025-02-04","n":"石頭段\n/繪製 - 1F~B4層 進出口停管設備 \n/通關機 + 訪客機 + B4 ~ 1F ~ 15F + R1F ~ R3F 層門禁","u":"","a":"李銘華","w":"簡宏義"},
  {"r":27,"p":"石頭段","d":"2025-02-05","n":"石頭\n/停管設備-樓層昇位圖\n/車位在席-系統架構圖","u":"","a":"李銘華","w":"簡宏義"},
  {"r":28,"p":"石頭段","d":"2025-02-18","n":"修改\n/車道控制箱 - 移位","u":"","a":"李銘華","w":"簡宏義"},
  {"r":29,"p":"石頭段","d":"2025-03-14","n":"石頭段\n/繪製 - B3 , B4層 增加\n動線指示燈箱","u":"","a":"李銘華","w":"簡宏義"},
  {"r":30,"p":"石頭段","d":"2025-03-18","n":"石頭段\n/繪製 - B1 , B2層 增加\n動線指示燈箱","u":"","a":"李銘華","w":"簡宏義"},
  {"r":31,"p":"石頭段","d":"2025-03-19","n":"石頭段\n/修改 繪製 - B1 , B4層 取消車位在席\n/B2~B4層 APS 移位置另一部電梯梯廳\n/1F - 立招888移位","u":"https://drive.google.com/drive/folders/1pC4VrRbSBK2-U54Hoigj-1IAAgYCkDTe?usp=drive_link","a":"李銘華","w":"簡宏義"},
  {"r":32,"p":"光武段","d":"2025-01-15","n":"光武段\n/繪製 - 1F - B4 層車道控制器 + 紅綠燈\n/繪製 - 1F ~ B4層停管設備管線","u":"https://drive.google.com/drive/folders/1jfrHmKbGcZegkb_0MbSo7wG05RA6ZcLa?usp=drive_link","a":"高祥林","w":"簡宏義"},
  {"r":33,"p":"東森林口","d":"2025-03-14","n":"東森林口\n/停管系統規劃 - B1汽機車入出口設備 + B1 ,B2,B3車位在席","u":"https://drive.google.com/drive/folders/10OUS7LwJkVn9nIolgucrw3aOM5ABqKg3?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":34,"p":"員榮醫院","d":"2025-02-27","n":"員榮醫院 - 停管設備-管線估算 1F~B3層","u":"https://drive.google.com/drive/folders/1Tth7HaSgZTH2FoFoRsnzrXyyqteLyIMX?usp=drive_link","a":"李銘華","w":"簡宏義"},
  {"r":35,"p":"晟峰精密廠辦大樓","d":"2025-03-13","n":"晟峰精密廠辦大樓\n/繪製 - B1汽車入出口設備 + 機車入口設備 及 各設備管線圖","u":"https://drive.google.com/drive/folders/1RLbRq24HbTl1rJOdY_Zntd9rK7_Y-Fie?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":37,"p":"桃園 C 基地","d":"2025-04-21","n":"桃園 C 基地 - 4/16收到新建築底圖\n/重新套基底圖面 1F~B3層\n/進出口停管設備 + 車位在席 + 車道控制器\n/及車位在席竟頭數量統計","u":"","a":"李銘華","w":"簡宏義"},
  {"r":38,"p":"桃園 C 基地","d":"2025-04-22","n":"修改 \n桃園C基地 \n/1F -一進一出車道-改成雙出車道出口\n/B1 - 汽車一進一出設備基座修改雙出出口車道\n/B2 - 機車出口基座改為45公分","u":"","a":"李銘華","w":"簡宏義"},
  {"r":40,"p":"桃園小檜溪","d":"2025-03-10","n":"桃園小檜溪 - 車格位變更\n/修改變更圖面 - B1 , B3 ,B4 層車格位 及EMT 管長度","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":42,"p":"桃園小檜溪","d":"2025-04-11","n":"桃園小檜溪 -\n/繪製 - 5層~11層竣工圖面","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":43,"p":"桃園小檜溪","d":"2025-04-14","n":"桃園小檜溪 -\n/繪製 - 11層~20層竣工圖面 + 屋頂RF1~RF3","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":44,"p":"桃園小檜溪","d":"2025-04-15","n":"桃園小檜溪 -\n/繪製 - 1層~4層-停管設備+通關機+門禁+訪客機\n竣工圖面","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":46,"p":"桃園蘆竹錦中段\n2025/01/03 - 最新建築底圖版本","d":"2025-01-22","n":"桃園蘆竹錦中段建築底圖更新\n停管設備+門禁設備重新套圖\n/B1 + 1F ~ 8F + R1 ~ R3","u":"https://drive.google.com/drive/folders/1O-nf_TScavE1PL8iphnmI5XznYd_lL4e?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":47,"p":"桃園蘆竹錦中段\n2025/01/03本","d":"2025-01-22","n":"停管設備+門禁設備重新套圖\n/B1 + 1F ~ 8F + R1 ~ R3 \n/繪製-停管+門禁設備管線昇位圖","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":48,"p":"海華金融中心","d":"2025-03-05","n":"海華金融中心 - PDF 檔\n/繪製CAD檔 -  1F 樓層平面圖 , 2F 樓層平面圖 \n/規劃3種方案 - 通關機+訪客機","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":49,"p":"停車管理系統架構圖","d":"2025-03-26","n":"繪製  - 停車管理系統\n/停車管理系統架構圖","u":"","a":"李銘華","w":"簡宏義"},
  {"r":50,"p":"國泰小檜溪/門禁4F修改管線配置","d":"2025-01-01","n":"1/1無法交給業務","u":"","a":"張舒婷","w":"簡宏毅"},
  {"r":51,"p":"國壽襄陽大樓","d":"2025-04-02","n":"國壽襄陽大樓 - 通關機+訪客(1F) + 停管\n/1F - 車道進出口停管設備 - 移至B1層","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":52,"p":"新竹巨城購物中心","d":"2025-01-23","n":"新竹巨城購物中心\n/繪製 - B3 , B4層-擺放樓層區域滿車燈設備10座","u":"","a":"高祥林","w":"簡宏義"},
  {"r":53,"p":"新竹巨城購物中心","d":"2025-03-31","n":"新竹巨城購物中心\n/繪製 - B3 , B4 臨停-停車分區圖 -車格編號","u":"https://drive.google.com/drive/folders/1w-kWMJdsiwldHPcnG1H-Sxu2xu67Dexp?usp=drive_link","a":"高崇仁","w":"簡宏義"},
  {"r":54,"p":"新店 央二","d":"2025-03-08","n":"新店 央二\n/繪製-1F停管限高架位置及限高架樣式","u":"","a":"李銘華","w":"簡宏義"},
  {"r":56,"p":"新店區斯馨段","d":"2025-01-10","n":"新店區斯馨段\n/1F ,B1 層,B2層 - 汽機車進出口停車設備配置","u":"","a":"李銘華","w":"簡宏義"},
  {"r":57,"p":"新店區斯馨段","d":"2025-01-14","n":"新店區斯馨段\n/繪製 - 停管系統昇位圖 , 車位在席系統架構圖 ,\n樓層紅綠燈昇位圖","u":"","a":"李銘華","w":"簡宏義"},
  {"r":58,"p":"新店區斯馨段","d":"2025-02-11","n":"新店區斯馨段\n/B4 ,B5 層 - 設計各層出口設備基座\n/B2 , B3-住戶區-出口設備基座","u":"","a":"李銘華","w":"簡宏義"},
  {"r":59,"p":"新店區斯馨段","d":"2025-02-12","n":"新店區斯馨段-第三方案\n/修改 - B1-進場設備基座 X1 , B2(住戶區)進場設備基座X1\n/ B1 - 出口設備基座 X2 , B1,B4,B5 - 車位在席鏡頭\n/ , B1,B4,B5-設置繳費機","u":"https://drive.google.com/drive/folders/1p_cIIoCSYkqUZXLfpwVDfTEkJvtnRqBn?usp=drive_link","a":"李銘華","w":"簡宏義"},
  {"r":60,"p":"新莊大魯閣","d":"2025-03-06","n":"新莊大魯閣 - PDF\n/繪製 - 停車場平面圖","u":"https://drive.google.com/drive/folders/1lCx158h3yLP1sPaDhnHr_cjmPNRcr4_P?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":63,"p":"寰宇","d":"2025-02-17","n":"量測 - 1F,B1~B4停管設備 + 緊急求救設備\n管線長度-估算","u":"https://drive.google.com/drive/folders/1ElSr4BAg8MbXAi4gmDmpeNB0mLbSTSDr?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":64,"p":"寰宇","d":"2025-02-21","n":"修改 \n/2F - 3F 行動辦公區 - 監視攝影機\n門禁設備集線器 及 CCTV監視攝影機集線器\n管線路徑","u":"https://drive.google.com/drive/folders/1rhZQKcx-FFw5R44xWDHPfHI2Z8zZznzZ?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":65,"p":"寰宇","d":"2025-02-24","n":"繪製-寰宇停車場-B1~B4層\n停車場動線指引燈箱","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":66,"p":"寰宇","d":"2025-03-12","n":"寰宇 - 2F行動辦公區\n/繪製 - 通關機 (兩道95)","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":67,"p":"寰宇","d":"2025-03-14","n":"寰宇 - 2F行動辦公區\n/繪製 - 通關機-管線圖","u":"","a":"章舒婷","w":"簡宏義"},
  {"r":68,"p":"龜山-新湖","d":"2025-01-03","n":"地籍圖 - 長 x 寬 面積尺寸\n/繪製 - 機車停車格 + 進出口停車管理設備","u":"","a":"高祥林","w":"簡宏義"},
  {"r":71,"p":"聯華實業","d":"2025-03-04","n":"繪製-聯華實業-1~8樓\n/1F -樓梯口-通關機 + 1F~8樓門禁設備","u":"","a":"李銘華","w":"簡宏義"},
  {"r":72,"p":"聯華實業","d":"2025-03-14","n":"聯華實業-停管系統-估算線長\n/繪製-停管設備管線 - 估算線長\n1F ~ B4 層","u":"","a":"李銘華","w":"簡宏義"},
  {"r":73,"p":"聯華實業","d":"2025-03-18","n":"聯華實業-門禁系統-估算線長\n/繪製-門禁設備備管線 - 估算線長\n1F ~ 11F + RF1~RF2","u":"","a":"李銘華","w":"簡宏義"},
  {"r":74,"p":"聯華實業","d":"2025-03-21","n":"聯華實業-門禁系統-修改\n/門禁讀頭設備 - 部分改為開門按鈕\n1F ~ 11F + RF1~RF2\n停管部分\n/B1汽車入口-改雙車道","u":"https://drive.google.com/drive/folders/1MQecSXjHzNSDy68sJmCRyAbwGa2IpEjO?usp=drive_link","a":"李銘華","w":"簡宏義"},
  {"r":75,"p":"聯華實業","d":"2025-04-24","n":"聯華實業\n/修改 -1F - 通關機位置移位 + 取消訪客機","u":"","a":"李銘華","w":"簡宏義"},
  {"r":76,"p":"馥華之道","d":"2025-03-25","n":"馥華之道\n/繪製 - 1F ~ B6層-各樓層停管設備及\n/1F - 住宅區+臨停區 - 汽機車入出口設備位置","u":"","a":"高祥林","w":"簡宏義"},
  {"r":77,"p":"繪製 - 停車進出設備 立面圖","d":"2025-01-16","n":"繪製-停車場-1進1出(共基座) , 單基座1進1出\n車辨2K8+繳費機 , 簡易車辨+字幕機+APS","u":"","a":"李銘華","w":"簡宏義"},
  {"r":78,"p":"乾坤測繪 -","d":"2025-05-05","n":"乾坤測繪 -\n/繪製 - 停管設備柵欄機位置","u":"https://drive.google.com/drive/folders/1WUAK8IK5P8ksmF_yQXDJgbYqBpNTRnh-?usp=drive_link","a":"吳哲帆","w":"簡宏義"},
  {"r":79,"p":"台南置地","d":"2025-05-08","n":"台南置地\n/修改-繪製行動辦公區 - 改走線槽架","u":"https://drive.google.com/drive/folders/17bUblF6BilEiF3Eri5zS8uhJrAvX7uPK?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":80,"p":"台南置地","d":"2025-05-09","n":"台南置地\n/套圖-行動辦公區 - 套上現場裝修圖面","u":"","a":"Tearo Lin","w":"簡宏義"},
  {"r":81,"p":"中華工程 雲宇宙","d":"2025-05-08","n":"中華工程 雲宇宙\n/修改圖面 - 圖例放大 , 刪除無相關圖面文字 , 及繪製封面索引表","u":"","a":"高祥林","w":"簡宏義"},
  {"r":82,"p":"中華工程 雲宇宙","d":"2025-05-09","n":"中華工程 雲宇宙\n/增加 - 停車場電腦收費系統架構圖 + 充電樁系統架構圖 + 充電樁系統配置圖","u":"https://drive.google.com/drive/folders/1drbF-MWgPyh5B0i88xc2Ze-Ot8OGFfnw?usp=drive_link","a":"高祥林","w":"簡宏義"},
  {"r":83,"p":"桃園小檜溪","d":"2025-05-09","n":"桃園小檜溪\n/協助-舒婷\n/小檜溪 - B3 ~ B4 層變動車格-修改管線","u":"https://drive.google.com/drive/folders/1xypCtNFNstRzT5sMN8YRhv_pY-yknrkP?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":84,"p":"桃園 C 基地","d":"2025-05-14","n":"桃園 C 基地 - 4/16收到新建築底圖\n/門禁系統設備 - 調整門禁數量","u":"","a":"Tearo Lin","w":"簡宏義"},
  {"r":85,"p":"台南置地","d":"2025-05-12","n":"台南置地\n/行動辦公區 - 門禁設備 + CCTV 監視設備計算線材米數","u":"https://drive.google.com/drive/folders/17bUblF6BilEiF3Eri5zS8uhJrAvX7uPK?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":86,"p":"田心段","d":"2025-05-15","n":"田心段\n/1F-通關機+訪客機+門禁 + 2F ~19 F 門禁設備+緊急壓扣","u":"https://drive.google.com/drive/folders/14lYg6yqfVSfJ1JTSIRzwJLTtjmTn0B5v?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":87,"p":"桃園 C 基地","d":"2025-05-16","n":"桃園 C 基地 - 4/16收到新建築底圖\n/B1~B3 層 - 停管設備數量 及 各樓層線材米數估算","u":"","a":"Tearo Lin","w":"簡宏義"},
  {"r":89,"p":"宏達雙十","d":"2025-05-19","n":"宏達雙十\n/繪製 -車道平面圖 + 設備 +管線","u":"https://drive.google.com/drive/folders/1bD2Ih54GkZOzn9MwzDWpjpa9SSN46bfT?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":90,"p":"田心段","d":"2025-05-20","n":"田心段\n/二修 - 1F 通關機 + 訪客機 +門禁\n/2F ~ 19 F 訪客平板+緊急求救壓扣\n/樓上層門禁設備 移除","u":"","a":"Tearo Lin","w":"簡宏義"},
  {"r":91,"p":"田心段","d":"2025-05-21","n":"田心段\n/二修 - 1F 通關機 + 訪客機 +門禁\n/2F ~ 19 F 訪客平板+緊急求救壓扣\n//B1~B5 層增加門讀頭+緊急對講機+緊急求救壓扣\n/屋突 一 層+ 加門讀頭+陽極鎖+陰極鎖","u":"https://drive.google.com/drive/folders/14lYg6yqfVSfJ1JTSIRzwJLTtjmTn0B5v?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":92,"p":"馥  御","d":"2025-05-22","n":"馥  御\n/整理 - 住宅區停管設備圖\n/1F , B1 , B2 停管設備整理合併成一張圖面","u":"https://drive.google.com/drive/folders/1XY0IphB0yQPrwk0iGhpSK2Tc_0HgGaHN?usp=drive_link","a":"高秉鈞","w":"簡宏義"},
  {"r":93,"p":"環  宇","d":"2025-05-22","n":"環  宇\n/1樓通關機 - 繪製現場實際尺寸\n/繪製 - 兩種通關機建議尺寸","u":"https://drive.google.com/drive/folders/1CKL_Mx8fxhG0ZqOFFGCPm5eH1rvaO-zu?usp=drive_link","a":"章舒婷","w":"簡宏義"},
  {"r":94,"p":"桃園 C 基地","d":"2025-05-28","n":"桃園 C 基地 - 4/16收到新建築底圖\n/繪製 - 樓上層 (訪客平板) - (參考田心段)","u":"https://drive.google.com/drive/folders/1z1czdWHmae_TG-f75Fo8o3GIY9Ykjj4a?usp=drive_link","a":"Tearo Lin","w":""},
  {"r":95,"p":"內湖矽塔中心","d":"2025-05-29","n":"內湖矽塔中\n/修改 - 機車車牌辨識 , 改 ETC遠距離讀卡機","u":"","a":"吳哲帆","w":""},
  {"r":96,"p":"桃園 C 基地","d":"2025-05-30","n":"桃園 C 基地\n/修改 - 停管B3 ,B2 ,B1 車辨鏡頭線槽\n/遇到防火鐵捲門需要修改繞道","u":"","a":"Tearo Lin","w":""},
  {"r":97,"p":"桃園 C 基地","d":"2025-06-03","n":"桃園 C 基地\n/去金隆科技公司討論\n/修改-繪製線槽合併至 - 車位在席線槽上","u":"","a":"Tearo Lin","w":""},
  {"r":98,"p":"桃園 C 基地","d":"2025-06-04","n":"桃園 C 基地\n/二次修改-繪製線槽合併至 - 車位在席線槽上","u":"","a":"Tearo Lin","w":""},
  {"r":99,"p":"桃園 C 基地","d":"2025-06-06","n":"桃園 C 基地\n/修改-樓上層 門禁設備 - 預留訪客平板 - 預留配管","u":"","a":"Tearo Lin","w":""},
  {"r":100,"p":"臻鼎時代大廈","d":"2025-06-09","n":"臻鼎時代大廈\n/繪製 - 停管設備\n/B1~B3 層出車位在席鏡頭","u":"","a":"高秉鈞","w":""},
  {"r":101,"p":"土城沛波 ,  信義經貿","d":"2025-06-10","n":"土城沛波 ,  信義經貿\n/繪製 - 充電樁配置位置圖","u":"","a":"張友山","w":""},
  {"r":102,"p":"石頭段","d":"2025-06-12","n":"石頭段\n/依據報價單 - 調整停管設備 + 門禁設備 + 通關機+訪客機\n/修改圖面","u":"","a":"張友山","w":""},
  {"r":103,"p":"中華工程 雲宇宙","d":"2025-06-12","n":"中華工程 雲宇宙\n/調整 - 圖面B1~B5建築底圖放大 ... 放置到不超出圖框","u":"","a":"彥廷","w":""},
  {"r":104,"p":"名遠廣場","d":"2025-06-13","n":"名遠廣場\n/繪製 - 停管設備 1F ~ 3F 設備放置","u":"","a":"高祥林","w":""},
  {"r":105,"p":"巨城購物中心","d":"2025-06-16","n":"","u":"","a":"高崇仁","w":""},
  {"r":106,"p":"桃園C基地","d":"2025-06-13","n":"桃園C基地\n/修改 1F -  停管設備 - 通關機+訪客機+門禁 分開\n拆成兩分圖檔 - 設備分開","u":"","a":"張友山","w":""},
  {"r":107,"p":"名遠廣場","d":"2025-06-17","n":"名遠廣場 - 新的建築底圖\n/重新套圖 - 停管設備 1F ~ 3F 設備放置","u":"","a":"高祥林","w":""},
  {"r":108,"p":"環  宇","d":"2025-06-25","n":"環  宇\n\n/繪製 - 現場實際配管竣工圖 , 門禁系統+停管設備","u":"","a":"章舒婷","w":""},
  {"r":110,"p":"宏達 尖福二","d":"2025-06-26","n":"宏達 尖福二\n/繪製 -平面圖 + 停管設備","u":"","a":"章舒婷","w":""},
  {"r":111,"p":"台南置地","d":"2025-06-26","n":"新裝修建築底圖\n/重新套圖 - 門禁系統設備 + CCTV監視設備重新移植套圖","u":"","a":"張友山","w":""},
  {"r":113,"p":"國壽襄陽大樓","d":"2025-06-30","n":"國壽襄陽大樓 \n/新建築底圖 - 重新套圖停管設備 \n/繪製 - 1F 通關機+訪客機+門禁設備 B6 ~1F , 2F ~3F \n4F ~10 F , 11F ~ 15F , 16 F ~ 24F , R1F~R3F","u":"","a":"章舒婷","w":""},
  {"r":114,"p":"台南置地","d":"2025-07-02","n":"台南置地 - 修改(業主刪除一間機房 S2 )\n/刪除S2機房點位 - 調整門禁設備 , CCTV監視設備 \n分別移至 S1 , S3 機房 重新估算線材米數","u":"","a":"張友山","w":""},
  {"r":115,"p":"桃園 C 基地","d":"2025-07-07","n":"桃園 C 基地\n/增加門禁點位 - 增加B1 - 防災中心, 管委會 , 4F旅館區管委會","u":"","a":"張友山","w":""},
  {"r":117,"p":"充電樁","d":"2025-07-04","n":"充電樁\n/繪製 - 充電樁立面圖 + 尺寸\n及充電樁正視圖 + 左右兩側側視圖 + 後視圖","u":"","a":"章舒婷","w":""},
  {"r":118,"p":"台南置地","d":"2025-07-07","n":"台南置地 - 修改 S1 機房移位\n/S1 機房移位 - 門禁設備 + 監視CCTV 管線重劃","u":"","a":"張友山","w":""},
  {"r":119,"p":"中華工程 雲宇宙","d":"2025-07-07","n":"中華工程 雲宇宙 - 修改在席鏡頭 1對3\n/修改 - B1 及B2車位在席鏡頭 1對3","u":"","a":"彥廷","w":""},
  {"r":120,"p":"忠泰建設","d":"2025-07-14","n":"忠泰建設","u":"","a":"張友山","w":""},
  {"r":121,"p":"中華工程 雲宇宙","d":"2025-07-14","n":"中華工程 雲宇宙\n/補畫 - 追加 (充電區域)車位在席鏡頭","u":"","a":"高祥林","w":""},
  {"r":122,"p":"寰宇","d":"2025-07-14","n":"寰宇 - 修改\n/2F - 2座通關機位置 修改","u":"https://drive.google.com/drive/folders/1QgTWuseOKfSB9OZnu64_WvmOCRE8Ra8p?usp=drive_link","a":"章舒婷","w":""},
  {"r":123,"p":"金仁寶","d":"2025-07-17","n":"金仁寶\n/繪製 - B3層車位在席","u":"https://drive.google.com/file/d/13NhHB6IxiiM-4J8u-LW0NqKoLQBpb8VD/view?usp=drive_link","a":"Tearo Lin","w":""},
  {"r":124,"p":"中華工程 雲宇宙","d":"2025-07-15","n":"中華工程 雲宇宙\n/印A3 圖紙 - 需要有比例\n調整A3紙張 比例 1/1000","u":"https://drive.google.com/file/d/1T6ND2xM3qkYATCqQmHv-bEGHaKtFf3jy/view?usp=drive_link","a":"彥廷","w":""},
  {"r":125,"p":"內湖矽塔中心","d":"2025-07-15","n":"內湖矽塔中心\n/修改 - 調整進出口基座","u":"https://drive.google.com/file/d/17o44VRdHXjeHlDSjE8aHoW9sxA_WeP5A/view?usp=drive_link","a":"吳哲帆","w":""},
  {"r":126,"p":"桃園 C 基地","d":"2025-07-18","n":"桃園 C 基\n/增加4F - 通關機 2座 (120)","u":"https://drive.google.com/file/d/1jW99X39xOk7zh3u6Dx3NJt610nVcuYDf/view?usp=drive_link","a":"張友山","w":""},
  {"r":127,"p":"世界廣場","d":"2025-07-22","n":"世界廣場\n/繪製 - 汽車,機車入出口設備規劃 , B1 ~ B4 停管規劃","u":"https://drive.google.com/file/d/1te9uIGrNEj_s4-s1EUAkF4FWYqRhRdzn/view?usp=drive_link","a":"張友山","w":""},
  {"r":128,"p":"馥華艾美","d":"2025-07-22","n":"馥華艾美 \n/ 繪製 B1~B3 充電樁位置及配電盤管線","u":"https://drive.google.com/file/d/1NVVA3jYOkG_ygZd03iOJILKF-ISWFFP2/view?usp=drive_link","a":"高崇仁","w":""},
  {"r":129,"p":"振興醫院","d":"2025-07-23","n":"振興醫院\n/繪製 - 1F車辨雙開 及 B2,B3層車在席鏡頭","u":"https://drive.google.com/file/d/1HA2Q-pKr1m4ctiOWxbP_Ye2-l36fPasT/view?usp=drive_link","a":"高祥林","w":""},
  {"r":130,"p":"國壽襄陽大樓","d":"2025-07-28","n":"國壽襄陽大樓\n/1F-通關機移位 , 訪客機增加一台","u":"https://drive.google.com/file/d/10x29DEn2akyWvu13toNYfjHA8zsEoS3w/view?usp=drive_link","a":"章舒婷","w":""},
  {"r":131,"p":"國壽襄陽大樓","d":"2025-07-30","n":"國壽襄陽大樓\n/B1~B5層-增加充電樁","u":"https://drive.google.com/file/d/1LrIrggSYtT7hMSftM8XNO5COC0CbVjOF/view?usp=drive_link","a":"章舒婷","w":""},
  {"r":132,"p":"國壽民生復興","d":"2025-07-31","n":"國壽民生復興\n/繪製 - 停管入出口設備及車位在席鏡頭 1F~B5","u":"https://drive.google.com/file/d/1I5W8UVUzkQYJxEIvppGR92VV3siUfvMY/view?usp=drive_link","a":"張友山","w":""},
  {"r":133,"p":"國壽民生復興","d":"2025-08-04","n":"國壽民生復興\n/繪製 - 1F通關機+訪客機, 2F~20F 門禁設備","u":"https://drive.google.com/file/d/19wjGzAwYb1X_c1RGadB_6JL4-Bcabtfg/view?usp=drive_link","a":"張友山","w":""},
  {"r":134,"p":"國壽襄陽大樓","d":"2025-08-05","n":"國壽襄陽大樓\n/修改 - 增加身障車格加裝充電樁","u":"https://drive.google.com/file/d/1-KVtzGlOcetGbgTNr8mioIhtusHqlYdg/view?usp=drive_link","a":"章舒婷","w":""},
  {"r":135,"p":"環宇","d":"2025-08-05","n":"環宇\n/修改 - 現場通關機淨寬尺寸","u":"https://drive.google.com/file/d/1YhD1pnS2wANNlR9RPzHo96eFFyiulCAq/view?usp=drive_link","a":"劉芸滋","w":""},
  {"r":136,"p":"聯華實業","d":"2025-08-06","n":"聯華實業\n/修改 - B1汽車入口位置 , 修改到1F車道處 \n\n聯華實業\n/修改  - B1汽車出口二出設備 , 調整修改為 汽車一出","u":"https://drive.google.com/file/d/1N8kGuctbM4F3RnYE1islZMXxrrB1kPdG/view?usp=drive_link","a":"張友山","w":""},
  {"r":137,"p":"振興醫院","d":"2025-08-08","n":"振興醫院\n/修改 - B1-汽車進出口設備調整(改295D) 基座縮短 \n及 1F ~ B3 設備管線.","u":"https://drive.google.com/drive/folders/1DPXXMRhf-e9fifDJEA8ZGpxveyeL9ukI?usp=drive_link","a":"高祥林","w":""},
  {"r":139,"p":"北區郵政物流中心","d":"2025-08-12","n":"北區郵政物流中心\n/繪製 - 1F 通關機兩處 , 一處95通關機 , 一處65兩道120道","u":"https://drive.google.com/drive/folders/1T-6TToIirfNn8Ibc-W8_1vz0ajVn2pJV?usp=drive_link","a":"章舒婷","w":""},
  {"r":140,"p":"聯華實業","d":"2025-08-13","n":"聯華實業\n/修改 - 1F 處通關機 改為圓柱型 , B1 梯廳前通關機 改為圓柱型","u":"","a":"張友山","w":""},
  {"r":141,"p":"聯華實業","d":"2025-08-13","n":"聯華實業\n/修改 - 1F 汽車入口移除軟質分隔桿及柵欄機改折臂 , B1 出口改折臂柵欄","u":"","a":"張友山","w":""},
  {"r":142,"p":"國壽民生復興","d":"2025-08-13","n":"國壽民生復興\n/增加 - B2快充7支 - B2+B3慢充33支 圖面補畫上去","u":"","a":"張友山","w":""},
  {"r":143,"p":"桃園C基地","d":"2025-08-17","n":"桃園C基\n/繪製 - 門禁系統-各樓層hub管線路 -及hub箱位置","u":"","a":"張友山","w":""},
  {"r":144,"p":"台南置地","d":"2025-08-18","n":"台南置地 - 修改 監視CCTV數量\n/業主修改 監視CCTV 數量及管線重劃","u":"https://drive.google.com/file/d/1YfNmRXm2HBvfR0wam6P28mHPOj8ory0G/view?usp=drive_link","a":"張友山","w":""},
  {"r":145,"p":"桃園C基地","d":"2025-08-20","n":"桃園C基\n/比對業主承辦 - 手上的停管規劃案(PSS) 圖檔 , \n跟我們現在最新的規劃設計 設備內容是否相同","u":"https://drive.google.com/file/d/14bKye5T9msILYxeVmwB4wXCYsvJr2arb/view?usp=drive_link","a":"張友山","w":""},
  {"r":146,"p":"桃園小檜溪","d":"2025-08-20","n":"桃園小檜溪\n/三井監造反映 - 小檜溪竣工圖建築底圖是舊圖\n/收到新底圖 - 更新B1 ~B4 建築底圖\n/圖面更新 -B1 ~B4 停管竣工圖","u":"https://drive.google.com/file/d/1_LQpkUnHkmCTG2fCDnonU6J1CN61rDVx/view?usp=drive_link","a":"章舒婷","w":""},
  {"r":147,"p":"桃園C基地","d":"2025-08-25","n":"桃園C基\n/A棟,B棟 增加身障門120","u":"https://drive.google.com/file/d/1UsmT4lc_6c54sXmCvP8IV2cl9bA5nAT-/view?usp=drive_link","a":"張友山","w":""},
  {"r":148,"p":"國壽民生復興","d":"2025-08-26","n":"國壽民生復興\n最新建築底圖\n/1F~B5曾停管規劃\n/1F-通關機+訪客機\n/2F~20F門禁 + R1F門禁","u":"https://drive.google.com/file/d/1Ul7FFQQvV559jH3rkndehYbCX4iz79qF/view?usp=drive_link","a":"張友山","w":""},
  {"r":149,"p":"禾力智博","d":"2025-08-28","n":"禾力智博\n/規劃 - 1F 通關機6道\n/B1~B3 梯廳各3道通關機","u":"https://drive.google.com/file/d/1maqXqDI7ypRucV_RYT0yyFFU-OM-ui-M/view?usp=drive_link","a":"林佑安","w":""},
  {"r":150,"p":"國壽民生復興","d":"2025-08-28","n":"國壽民生復興\n/增加 - 1F 大廳-固定式攝影機\n電梯內 - 增加半球型攝影機","u":"https://drive.google.com/file/d/1si1JYxq3kwh8qNwuzkIuiJg2WyAYtDTb/view?usp=drive_link","a":"張友山","w":""},
  {"r":151,"p":"金仁寶","d":"2025-09-05","n":"金仁寶\n/1.梯間繳費機管線拉到車道上\n2.Ｂ3機車出口修改為兩道\n3.Ｂ2汽車入口三道往後移\n4.Ｂ2下B3-增加月租-車辨+柵欄機\n5.一樓立招到限高架 再到B2管道間","u":"https://drive.google.com/file/d/1b-5XVOONwsoyySMfAa96VcR9IgnzAsK_/view?usp=drive_link","a":"張友山","w":""},
  {"r":152,"p":"東森電視","d":"2025-09-01","n":"東森電視\n/繪製 - 1F通關機+訪客機+電梯讀頭","u":"https://drive.google.com/file/d/1PLDJv72Rpy-mjUEh-4FwfvX_mxYGrwsm/view?usp=drive_link","a":"章舒婷","w":""},
  {"r":153,"p":"福隆建設","d":"2025-09-08","n":"福隆建設\n/繪製 - 1F ~ B5層 - 停管設備 , 及 1F 汽機車入出口設備","u":"https://drive.google.com/file/d/1F_bF9u0c27MVma4fyO4CzC35IUF16B_z/view?usp=drive_link","a":"張友山","w":""},
  {"r":154,"p":"禾力智博","d":"2025-09-12","n":"禾力智博\n/修改 - 1F 通關機移位及另一處通關機改為65兩道\nB1通關機保留 , B2,B3 層通關機移除","u":"https://drive.google.com/drive/folders/1dlpaOys1GAQ9sGowvbUIG8H30ouA1hd9?usp=drive_link","a":"林佑安","w":""},
  {"r":156,"p":"中賓BOT 案圖面","d":"2025-09-25","n":"中賓BOT 案圖面 \n/繪製 - 1F~ B1 , 2F~4F 停管設備規劃\n/繪製 -汽車入出口設備 , 機車入出口設備\n/繪製 -車位在席鏡頭 , 9台APS , 108CCTV , 30格充電樁","u":"https://drive.google.com/drive/folders/1KGRMU1NNbFQMoNu-bGdeXJE6YEmcA3ao?usp=drive_link","a":"Tearo Lin","w":""},
  {"r":157,"p":"福隆建設","d":"2025-09-25","n":"福隆建設\n/繪製 - 1F ~ B5層 - 停車系統架構圖 + 樓層昇位圖","u":"https://drive.google.com/drive/folders/17_lZpwNFEOjw5Mwa0pxGS3XNTJobNQbj?usp=drive_link","a":"張友山","w":""},
  {"r":158,"p":"環宇","d":"2025-09-30","n":"環宇\n/修改 - 現場B1入出口設備基座會勘修正圖","u":"https://drive.google.com/drive/folders/10shy3kNRLq8cnMDBdzTe2eTifpYXrX_i?usp=drive_link","a":"章舒婷 / 張友山","w":""},
  {"r":159,"p":"仁義","d":"2025-10-01","n":"仁義 - 停車場畫案\n/繪製 - 汽機車停車場進入口 - 方案一 , 方案二\n/繪製 - 場內行車動線","u":"https://drive.google.com/drive/folders/1EgLvViwWv9JvwwQpLd2b0ZG6a149IH67?usp=drive_link","a":"高秉鈞","w":""},
  {"r":160,"p":"民主段","d":"2025-10-01","n":"民主段\n/繪製 - 管線圖","u":"https://drive.google.com/drive/folders/1EzoGW2DhlyzwTUkXEKmMW1kRwZHlxVj_?usp=drive_link","a":"高秉鈞","w":""},
  {"r":161,"p":"桃園C基地","d":"2025-10-02","n":"桃園C基地  - 最新0917底圖\n/修改 - 建築師 -  改通關機 各四道  Aps增加  位置改   \n訪客機 數量減少  位置改","u":"https://drive.google.com/drive/folders/1KpB9voxcQpRnw8hm2jldiPKMa7VzEdne?usp=drive_link","a":"張友山","w":""},
  {"r":162,"p":"國壽民生復興","d":"2025-10-07","n":"國壽民生復興 - 1002更新底圖\n/建築底圖更新 - 1F~B5停管設備\n/1F -通關機+門禁 + 2F~20 F門禁 + R1F層 門禁設備\n重新套圖更新","u":"https://drive.google.com/drive/folders/1aFVFm1E7xliQI27mjAWrL7tA-n9tilBG?usp=drive_link","a":"張友山","w":""},
  {"r":163,"p":"馥華艾美","d":"2025-10-07","n":"馥華艾美\n/ 馥華艾美 - b1 , b2充電樁.... 管線繪製\n/各充電樁拉繪製管限至分電盤","u":"https://drive.google.com/drive/folders/1ve-keXOyn5Pj-8LbEgGpWVndOZbBG7Nd?usp=drive_link","a":"高秉鈞","w":""},
  {"r":164,"p":"林口長庚","d":"2025-10-09","n":"林口長庚\n/規畫 - B1~B3 層停車設備 , 及 B1 汽車入出口基座設備","u":"https://drive.google.com/drive/folders/1ZcB6BoRAKeJsDLXlFrH6GcOD-ckMDO0Q?usp=drive_link","a":"高秉鈞","w":""},
  {"r":165,"p":"林口長庚","d":"2025-10-15","n":"林口長 - 取得1F平面圖\n/規劃 - 1F 停管設備 + 停管設備平面圖+收費系統架構圖\n+在席系統架構圖+樓層昇位圖+充電樁架構圖","u":"https://drive.google.com/drive/folders/1ZcB6BoRAKeJsDLXlFrH6GcOD-ckMDO0Q?usp=drive_link","a":"高秉鈞","w":""},
  {"r":167,"p":"繪製 - 掃地機器人\nCC1 + MT1 Max + 閃電俠","d":"2025-10-29","n":"繪製 - 掃地機器人\nCC1 + MT1 Max + 閃電俠","u":"https://drive.google.com/drive/folders/13_xc_b76zEFaabOcjOqedMYY_AGoxZkX?usp=drive_link","a":"Tearo Lin","w":""},
  {"r":169,"p":"中賓BOT 案圖面","d":"2025-11-05","n":"中賓BOT \n/繪製 - 停管設備電力需求表","u":"https://drive.google.com/drive/folders/1wX0FtNXD_N2pSLUQ0wKFIeSNf_1k67oe?usp=drive_link","a":"Tearo Lin","w":""},
  {"r":170,"p":"晟峰精密廠辦大樓","d":"2025-11-07","n":"晟峰精密廠辦大樓\n//繪製 -  1F ~ B4 停管管線圖 +設備數量表","u":"https://drive.google.com/drive/folders/1T_FEbI2UdeEvlUrvGwGbs8gDYduF6bB-?usp=drive_link","a":"張友山","w":""},
  {"r":171,"p":"環宇","d":"2025-11-07","n":"環宇\n//繪製 - 停管1F~B4 停管設備竣工圖\n/繪製 - 1F ~通關機+ 2F+3F 門禁設備+CCTV 門禁設備竣工圖","u":"https://drive.google.com/drive/folders/1pjK4OeYxTTE4UmmyEtAJYedkfdtq_vx-?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":172,"p":"寶豐隆專案","d":"2025-11-21","n":"寶豐隆專案\n//繪製規劃 - 停管設備 1F~B6 層\n//繪製規劃 - 通關機+訪客機+門禁系統\n1F ~ 27F+RF1~RF3","u":"https://drive.google.com/drive/folders/1M7zFOUB_ev7gBI5yLhcUcOHBn0YhuIOO?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":173,"p":"土城沛波-1樓員工餐廳","d":"2025-11-13","n":"土城沛波-1樓員工餐廳\n/繪製-追加1樓門禁讀頭+陽極鎖+按鈕開關 - 管路圖","u":"https://drive.google.com/drive/folders/1CdZWTLUa6yOnKfx2LvtkuZAcwo9zvYaB?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":174,"p":"東森電視","d":"2025-11-13","n":"東森電視\n/繪製 - 1F-再增加通關機+訪客機+梯控 + 及管線+B1防災中心","u":"https://drive.google.com/drive/folders/1BjCpWgLj7yC4Xhbmkp6aLCLONlbOlOR-?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":175,"p":"環宇 - 停管設備 -竣工圖","d":"2025-11-13","n":"環宇 - 停管設備 -竣工圖\n/繪製竣工圖 - 1F~B4 停管設備+緊急求救+導引看板","u":"https://drive.google.com/drive/folders/1_iNZWvjNPNpNvQGmtq2j-xp-YmlctiYp?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":176,"p":"國泰仁愛總部大樓-","d":"2025-11-25","n":"國泰仁愛總部大樓 - 繪製藍圖\n/手繪藍圖 - 建築結構藍圖","u":"https://drive.google.com/drive/folders/1uk6S-pYmlKPUC2eiCHdytEU3qxCztV1h?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":177,"p":"埔心安居","d":"2025-11-25","n":"埔心安居 - 規劃停管設備\n/繪製- 1F ~ B3 層停管設備+ 車位在席鏡頭","u":"https://drive.google.com/drive/folders/1oHGzx8i6cvQFTByf5M6i4rYGQyZA87S9?usp=drive_link","a":"高秉鈞","w":"簡宏義"},
  {"r":178,"p":"東森電視","d":"2025-11-26","n":"東森電視 - 規劃停管設備 \n/ 繪製 - 1F ~ B4 層停管設備 +車位在席鏡頭","u":"https://drive.google.com/drive/folders/1YUCwdg8bivZk-ofoyvQR8MemxMt812qN?usp=drive_link","a":"高祥林","w":"簡宏義"},
  {"r":179,"p":"國泰仁愛總部大樓-","d":"2025-11-26","n":"國泰仁愛總部大樓-規畫通關機\n/繪製 - 4道65寬+身障門","u":"https://drive.google.com/drive/folders/1_NoKj_ZPtQ-hEsbqxFliYR2kX1hEW2BO?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":180,"p":"東森林口","d":"2025-12-03","n":"東森林口 - 規劃停管設備\n/繪製 -  1F ~ B4 層停管設備+ 汽車+機車入出口設備","u":"https://drive.google.com/drive/folders/19puk0MT8Ojjzfwr52FxgvzYREzd0qnON?usp=drive_link","a":"高祥林","w":"簡宏義"},
  {"r":181,"p":"信義經貿","d":"2025-11-28","n":"信義經貿 - 1F通關機竣工圖\n/ 繪製 - 1F通關機設備 及門禁系統設備竣工圖","u":"https://drive.google.com/drive/folders/1URARtNrtsHNnjCjMdeK368qFaVt9_swA?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":182,"p":"新莊好市多","d":"2025-11-28","n":"新莊好市多 - 繪製1F停館管線圖","u":"https://drive.google.com/drive/folders/1rvO3w44CbyufpnYofjWbgVIgbGPsXZEk?usp=drive_link","a":"高崇仁","w":"簡宏義"},
  {"r":183,"p":"允將","d":"2025-12-07","n":"允將 - 繪製規劃\n/1F~B9 - 停管設備規劃\n/1F -通關機+訪客機\n/2F ~ 40F -門禁設備 + RF1~RF2+RF","u":"https://drive.google.com/drive/folders/192mM1BZw11wumXeFOpZpPqD19hKGPmvD?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":184,"p":"PSS -柵欄機 尺寸","d":"2025-12-09","n":"PSS -柵欄機 尺寸\n/繪製 - 公司柵欄機尺寸正視 , 側視 , 府試圖","u":"https://drive.google.com/file/d/12LrraFTj9jOFmzzEPUpSmKvt6pxH_uuV/view?usp=drive_link","a":"高秉鈞","w":"簡宏義"},
  {"r":185,"p":"允將","d":"2025-12-12","n":"允將 - 繪製 樓層昇位圖\n/1F~B9 - 停管設備規劃\n/1F -通關機+訪客機\n/2F ~ 40F -門禁設備 + RF1~RF2+RF","u":"https://drive.google.com/drive/folders/13kIP0Ta-oDsX1EoXfbtM33Bx2TQTeaVj?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":186,"p":"桃園錦中段","d":"2025-12-12","n":"桃園錦中段 - 調整數量配合標單\n/調整 - 停管設備\n/配合標單數量-修改1F~B1平面圖","u":"https://drive.google.com/drive/folders/1vxKAEl9Gz5KW06rg5rNDGcts6E-QeC2u?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":187,"p":"國壽民生復興","d":"2025-12-15","n":"國壽民生復興 - 12/12 新建築底圖\n/重新套圖 - 1F ~  B5層停管設備\n/1F通關機+訪客機 + 2F ~ 20 F + R1F -門禁設備","u":"https://drive.google.com/drive/folders/1TLqMtX48T7qDuJBUR83RFfu9YCyFT-W2?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":188,"p":"竹陞新大樓","d":"2025-12-16","n":"竹陞新大樓 - 更換設備\n/停管設備 - 車格位超音波全部換成車位在席鏡頭\n/B1 ~ B3層 - 2F ~ 4F","u":"https://drive.google.com/drive/folders/1e7sZ4WEsohEL3WTvth13Y4qh4R9BOYEj?usp=drive_link","a":"高秉鈞","w":"簡宏義"},
  {"r":189,"p":"桃園C基地","d":"2026-01-12","n":"桃園C基 - 1216最新建築底圖\n/重新停管設備套圖\n/1F ~ B3 層停管設備 - 套圖","u":"https://drive.google.com/drive/folders/1iFbjiZmK4HXo1YZiR472daBHqDCGiS3m?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":190,"p":"寶豐隆專案","d":"2025-12-16","n":"寶豐隆專案\n//建檔 - EXCEL 設備數量統計表\n/停管設備 1F~B6 層\n/通關機+訪客機+門禁系統\n1F ~ 27F+RF1~RF3","u":"https://drive.google.com/drive/folders/1fAjb9IQe8rU2bytuRo4FlooE3ne4CXDu?usp=drive_link","a":"Tearo Lin","w":"簡宏義"},
  {"r":191,"p":"國壽民生復興","d":"2025-12-17","n":"國壽民生復興 - //建檔 - EXCEL 設備數量統計表\n/1F ~  B5層停管設備\n/1F通關機+訪客機 + 2F ~ 20 F + R1F -門禁設備","u":"https://docs.google.com/spreadsheets/d/15JHIJ5cA_8Iqy6XkDXMwMX6uxTnjb4ql/edit?usp=drive_link&ouid=108029360005033623249&rtpof=true&sd=true","a":"張友山","w":"簡宏義"},
  {"r":192,"p":"國壽民生復興","d":"2025-12-22","n":"國壽民生復興 - 管線估算","u":"https://drive.google.com/drive/folders/1V7VU7H-VexYOLY2I13BIQ4N6WDUmD-hw?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":193,"p":"大江購物中心","d":"2026-01-05","n":"大江購物中心 - 停管設備規劃\n超音波 + 燈號","u":"https://drive.google.com/drive/folders/1ojMfnpV-YN1xSYspJr07HSdy5s8wt7ST?usp=drive_link","a":"高秉鈞","w":"簡宏義"},
  {"r":194,"p":"中華工程 雲宇宙","d":"2025-12-26","n":"中華工程 雲宇宙\n修改 - B1 VIP 區\n修改汽車入出口設備 , 改為兩進兩出","u":"https://drive.google.com/drive/folders/1RyilFn2sZyJTzsEeWNTjT6_BAlh-dr1k?usp=drive_link","a":"高祥林","w":"簡宏義"},
  {"r":195,"p":"國壽民生復興","d":"2025-12-26","n":"國壽民生復興\n整合圖面 - 門禁1F~20F+R1F\n停管圖面 1F ~ B5層\n合併在同一支CAD 檔案","u":"https://drive.google.com/file/d/17y0NwjxS-joBqljJssYuMDfYtdEAbZKe/view?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":196,"p":"埔心安居","d":"2025-12-29","n":"埔心安居 - 更新建築底圖12/29","u":"https://drive.google.com/drive/folders/17kX7o98p2GMe0q_cRlsct4PAf_PI8aYw?usp=drive_link","a":"高秉鈞","w":"簡宏義"},
  {"r":197,"p":"金仁寶","d":"2026-01-06","n":"金仁寶 - 修改圖面","u":"https://drive.google.com/drive/folders/1gRiApmoOcAS-VAg0p_C47oqLXaqvEBvn?usp=drive_link","a":"Kevin Chen","w":"簡宏義"},
  {"r":198,"p":"中華工程 雲宇宙","d":"2026-01-02","n":"中華工程 雲宇宙\n修改 - 1F\n限高架-位置微調","u":"https://drive.google.com/drive/folders/1myLSSkRpEznhYqJk_Tui_r7qTWKV-Thm?usp=drive_link","a":"Vincent","w":"簡宏義"},
  {"r":199,"p":"中華工程 雲宇宙","d":"2026-01-06","n":"中華工程 雲宇宙 ... 甲區B1 - 機車入口基座尺寸-放大圖\n , VIP 汽車區 - 入口基座尺寸-放大圖 , B2 - 月租入口基座尺寸-放大圖 , 臨停區入口基座尺寸-放大圖 , 充電樁汽車入口設備基座 尺寸-放大圖\n\n乙區B1 - 機車出口基座尺寸-放大圖\n , VIP 汽車區 - 出口基座尺寸-放大圖 , B2 - 月租出口基座尺寸-放大圖 , 臨停區出口基座尺寸-放大圖 , 充電樁汽車出口設備基座 尺寸-放大圖","u":"https://drive.google.com/drive/folders/1fBC2ySpgURk6RbRpOd37_w2GXV_oUYFC?usp=drive_link","a":"Vincent","w":"簡宏義"},
  {"r":200,"p":"桃園錦中段","d":"2026-01-07","n":"桃園錦中段\n/徽幟 -彥均副理手劃入出口管線圖 , \n轉繪成 CAD 圖檔","u":"https://drive.google.com/drive/folders/1V2QGvxSx428h1yP86P0U4tYU9S9bKWVC?usp=drive_link","a":"彥均","w":"簡宏義"},
  {"r":201,"p":"國壽民生復興","d":"2026-01-09","n":"國壽民生復興\n/繪製 - 停管設備+通關機+訪客機+門禁系統架構-昇位圖","u":"https://drive.google.com/drive/folders/12OHuHNkyj8xMonB8woNaUwT-Ky3rhPZp?usp=drive_link","a":"張友山","w":"簡宏義"},
  {"r":202,"p":"中華工程 雲宇宙","d":"2026-01-12","n":"中華工程 雲宇宙 - 清圖\n/整理 - 1F ~ B5 層 - (刪除不要的線條)\n/出圖 - 1F ~B5層正式送審圖框","u":"https://drive.google.com/drive/folders/1ebQ2mZHF127JI5TOOXHOlkiGe0w-KwUT?usp=drive_link","a":"Vincent","w":"簡宏義"},
  {"r":203,"p":"大江購物中心","d":"2026-01-12","n":"大江購物中心 - 停管設備規劃\n/增加 - 樓層計數滿車燈 + 樓層區域計數滿車燈","u":"https://drive.google.com/drive/folders/1L6ObJJ0SW6ooJkn_9-K1qGjOfYXgUN_G?usp=drive_link","a":"高秉鈞","w":"簡宏義"},
  {"r":204,"p":"中華工程 雲宇宙","d":"2026-01-27","n":"中華工程 雲宇宙 - 依據標單\n/ 依據報價標單-調整 B2充電樁數量","u":"https://drive.google.com/drive/folders/1kqt6Q1Dtsk3bMX6HE2FEKYcLBYMkK0OY?usp=drive_link","a":"Vincent","w":""},
  {"r":205,"p":"國壽民生復興","d":"2026-02-09","n":"民生復興 .... 修改圖面及設備數量\n/修改 - 2F~ 20F+RF1 門禁訪客平板數量 及部分樓層只配預埋管\n/製作EXCEL - 統計門禁+通關機+訪客機設備數量 1F ~20F+RF1\n/停管設備數量 1F ~ B5 層 + B3~B5 繳費機配置預留管","u":"https://drive.google.com/drive/folders/1PInWw3G0J9rQbkQwqrpsjETNM-d7Hkli?usp=drive_link","a":"張友山","w":""},
  {"r":206,"p":"新店區斯馨段","d":"2026-02-10","n":"新店區斯馨段 - 修改\n/B1車道入口 - 改為雙入車道 , 增加指示燈相","u":"https://drive.google.com/drive/folders/1jN5N9ARdXWykN2wyzXrwzSeofViMKUcz?usp=drive_link","a":"Kevin Chen","w":""},
  {"r":207,"p":"桃園小檜溪","d":"2026-02-11","n":"桃園小檜溪 - 追加施作充電樁\n/修改 - B2層充電盤1 , 盤2 - 充電管線車格位","u":"https://drive.google.com/drive/folders/1aIqTntbHBuyUlIh4D9PsgSEQb2ZM-15l?usp=drive_link","a":"Neil","w":""},
  {"r":208,"p":"國壽民生復興","d":"2026-02-24","n":"","u":"","a":"張友山","w":""},
  {"r":209,"p":"桃園錦中段","d":"2026-03-05","n":"","u":"","a":"張友山","w":""},
  {"r":210,"p":"內湖TDS","d":"2026-03-09","n":"內湖TDS  - 停管設備規劃\n/B1 機車入車口設備基座 , 汽車入出口設備基座\n/B2 - 車位在席\n/ B2 B3 充電樁配置\n/B1 ~B4 車道控制器+紅綠燈","u":"https://drive.google.com/drive/folders/15MR_7Yy7g6xKb_ieKnXNDBazSuWLWvfA?usp=drive_link","a":"高祥林","w":""},
  {"r":211,"p":"聯發科竹北高鐵大樓","d":"2026-03-19","n":"聯發科竹北高鐵大樓\n/ 1F ~ B5 停車管理設備規劃","u":"https://drive.google.com/drive/folders/1EJx1dUlh3zmAJc8k4vYZSDUJy9sEol1n?usp=drive_link","a":"KEVIN","w":""},
  {"r":212,"p":"聯發科竹科新廠辦公大樓","d":"2026-03-19","n":"聯發科竹科新廠辦公大樓  - 停管設備規劃\n/1F  -   B4 停車管理設備規劃\n/車位在席 + 車道紅綠燈 + 行車動線","u":"https://drive.google.com/drive/folders/1fo5PzXcf6MXRtaqW4uO2zCsVf_bf_sOe?usp=drive_link","a":"KEVIN","w":""},
  {"r":213,"p":"敦南都更 (寶豐隆專案)","d":"2026-03-20","n":"敦南都更 (寶豐隆專案) 更新底圖\n/停管 - 1F ~ B6 層 - 停管圖設備套圖\n/通關機+門禁 - 1F 通關機+訪客機 \n2F+3F+4F+5F+6F~24F + 7F+ 11F+12F+25F+26F+27 門禁設備套圖","u":"https://drive.google.com/drive/folders/1HF_mbL1RSlaA0anjTS-LuCCT16Iwtepe?usp=drive_link","a":"張友山","w":""},
  {"r":214,"p":"桃園小檜溪 - 6樓行動辦公室","d":"2026-03-23","n":"桃園小檜溪 - 6樓行動辦公室\n/繪製-6樓門禁設備\n/繪製-監視攝影CCTV","u":"https://drive.google.com/drive/folders/1Gs1tvhrNrVd5N4hsEYOS1y8GsXpfPgHo?usp=drive_link","a":"張友山","w":""},
  {"r":215,"p":"內湖TDS  - 停管設備規劃 - 第三版","d":"2026-03-23","n":"汽車入出口設備被基座\n/B1設備-調整進出口設備基座位置","u":"https://drive.google.com/drive/folders/1SGg7pHDbaFXkREwzWdfLNHHTJdRYGwOR?usp=drive_link","a":"高祥林 / 高秉鈞","w":""},
  {"r":216,"p":"昌益親仁段","d":"2026-03-23","n":"昌益親仁段 - 規劃停車管理設備\n/繪製 - 1F 車道停車設備 , 限高架 , 滿車燈 , 出車警示燈\n/繪製 - B1 - 汽車入出口設備基座 + 機車入出口設備基座 \n/繪製 - B1 ~ B3層停車管理設備","u":"https://drive.google.com/drive/folders/1QuyuTbStE3P15ee-ygA06NwFSaEaH49c?usp=drive_link","a":"高祥林","w":""},
  {"r":217,"p":"桃園錦中段","d":"2026-03-26","n":"桃園錦中段 - 繪製施工圖 (給元利配管施工圖)\n/繪製 - 1F 停管設備+通關機+訪客機 + B1停管設備配管平面圖 - 給元利配管 ....","u":"https://drive.google.com/drive/folders/1HnmPnYudFRVhBU5Es3UwyhmFVD1T-jTT?usp=drive_link","a":"阿咸","w":""},
  {"r":218,"p":"聯發科竹科新廠辦公大樓","d":"2026-03-31","n":"聯發科竹科新廠辦公大樓 - 繪製管線圖\n/繪製 - 1F~ B4 層水電配置管線圖","u":"https://drive.google.com/drive/folders/13nkdk-JxOp3jDyl0lqV_hgWg_MjAMCzX?usp=drive_link","a":"KEVIN","w":""},
  {"r":219,"p":"聯發科竹北高鐵大樓","d":"2026-04-02","n":"聯發科竹北高鐵大樓 - 繪製管線圖\n/繪製 - 1F 水電配置管線圖","u":"https://drive.google.com/drive/folders/1uI_IbmZaSDdFurAiKdpLSB4HwXi48IfP?usp=drive_link","a":"KEVIN","w":""},
  {"r":220,"p":"內湖TDS","d":"2026-04-03","n":"內湖TDS  - 停管設備規劃- 第四版\n/B3 , B4 層增加車位在席鏡頭\n/修改 - B2 ,  B3 充電樁位置\n/ 增加 - 索引圖 + 停車管理系統架構圖 + 車位在席架構圖 + 停管設備昇位圖 + 充電樁架構圖","u":"https://drive.google.com/file/d/1lGJamEv4Tx5InC1cw37AftWHaNYXdUby/view?usp=drive_link","a":"高祥林","w":""},
  {"r":221,"p":"國家考場","d":"2026-04-02","n":"國家考場\n/停車設備規畫","u":"https://drive.google.com/drive/folders/1mFW6wmzSEmGugYBnHsZpjFHerZp-8D1a?usp=drive_link","a":"高祥林","w":""},
  {"r":222,"p":"內湖TDS","d":"2026-04-16","n":"內湖TDS  - 停管設備規劃- 第五版\n/1F-機車車道-1樓車偵箱改右邊花圃\n/B1貨車停車格也要坐在席 \n/B1管理室改收發室\n/B2 - 充電樁部分位置修改至右側靠牆\n/B3 - 充電樁部分位置修改至右側靠牆","u":"https://drive.google.com/drive/folders/1ZmKCbPtTYuElYoUv_fj-iBEHgHYU0vHm?usp=drive_link","a":"高祥林","w":""},
  {"r":223,"p":"內湖TDS","d":"2026-04-20","n":"內湖TDS  - 停管設備規劃- 第六版\n/更換 - 對方設計單位圖框 \n/修改 - B1~B4 層平面圖車位在席線槽 圖面標示線槽高度 \n/轉印 - 1F ~ B4層停管設備平面圖","u":"https://drive.google.com/drive/folders/1VnXmXuWLfXmdU7dm26so2U22gtlYeKPX?usp=drive_link","a":"高祥林","w":""},
  {"r":224,"p":"繪製 -整理停管設備 , 門禁設備 , 通關機 , \n掃地機器人-CC1+MT1+閃電俠圖面","d":"2026-04-23","n":"繪製 -整理停管設備 , 門禁設備 , 通關機 , 掃地機器人-CC1+MT1+閃電俠圖面\n/停車場系統架構圖 , 停車場設備樓層昇位圖 管理室-電腦機櫃圖\n/APT-雷達+汽車-一進一出  , APT-線圈+汽車+一進一出 ,AJ2K8+紅黃牌重機 ,APT-線圈-機車+汽車+一進一出\n/整理圖檔 - 放置PSS雲端存放","u":"https://drive.google.com/drive/folders/1dgpAsMY3l7mbkCkKukQu-DxG-Uc_nuw1?usp=drive_link","a":"","w":""},
  {"r":225,"p":"大江購物中心","d":"2026-05-20","n":"大江購物中心 - 停管設備規劃\nB1~B3客戶底圖梯廳機房空間變更\n/修改B1+B2局部車位\n/B1+B2+B3繳費機位置","u":"https://drive.google.com/drive/folders/1zD733pz5VcxFKny1OoGfAoNbyAtr2YWA?usp=drive_link","a":"高秉鈞","w":""},
  {"r":226,"p":"長榮國際大樓","d":"2026-05-15","n":"長榮國際大樓-停管設備規劃","u":"https://drive.google.com/drive/folders/1QTRxNIVHNA-X5QmZnusymBCIaNpvrqXF?usp=drive_link","a":"張友山","w":""},
  {"r":227,"p":"國泰沛坡大樓6樓","d":"2026-05-21","n":"國泰沛坡六樓-門禁設備管線竣工圖\n/修改通關機、大門門禁","u":"https://drive.google.com/file/d/142__83aCH7bHrX4a241Abj8ix5jtDXo7/view?usp=drive_link","a":"陳彥均","w":""},
  {"r":228,"p":"國泰沛坡大樓6樓","d":"2026-05-22","n":"國泰沛坡六樓-門禁設備管線竣工圖、大門門禁立面\n/修改通關機、大門門禁\n/繪製立面圖","u":"https://drive.google.com/file/d/1Qf53ksTm_Gk4aHxhR5vgkeJ6Pasrpv8J/view?usp=drive_link","a":"陳彥均","w":""},
  {"r":229,"p":"翡麗琚","d":"2026-05-27","n":"翡麗居_停管平面圖\n/1F汽車一進一出、機車單車道雙向\n/B1F~B4F進出感應線圈+紅綠燈","u":"https://drive.google.com/drive/folders/1Gt4Qq8zXHTmmmzMJY_kP-FSLesRY-AGT?usp=drive_link","a":"高祥林","w":""},
  {"r":230,"p":"大巨蛋-7樓廁所","d":"2026-05-28","n":"大巨蛋-7樓廁所 智慧廁所 平面圖+昇位圖+系統架構圖\n/繪製系統架構圖icon描邊、系統架構圖\n/繪製智慧廁所設備","u":"https://drive.google.com/drive/folders/1cHCGizMQCnuKAo9iWe5he9C9nCElcchw?usp=drive_link","a":"kevin","w":""},
  {"r":231,"p":"國泰世華","d":"2026-06-04","n":"國泰世華-1F通關機設備點位","u":"https://drive.google.com/drive/folders/1X1EVSFvUEoA98NQv3y71ZwzND_tBjAFV?usp=drive_link","a":"張友山","w":""},
  {"r":232,"p":"聯發科高鐵大樓","d":"2026-06-15","n":"聯發科高鐵大樓-圖面修改（圖框刪除、減速墊刪除、新增在席）","u":"https://drive.google.com/drive/folders/1Ge4GZvquUh11joQmte75j0yz4UjwnQXC?usp=drive_link","a":"kevin","w":""},
  {"r":233,"p":"翡麗琚","d":"2026-06-10","n":"翡麗琚-更新底圖","u":"https://drive.google.com/file/d/1Thq8dmtHQDMWRGO15O5Oe6-Z5X7KFrd_/view?usp=drive_link","a":"高祥林","w":""},
  {"r":234,"p":"聯發科竹科新廠辦公大樓","d":"2026-06-15","n":"圖面修改（圖框刪除、減速墊刪除）","u":"https://drive.google.com/drive/folders/1haxoc2bqIfgDgjsqhiy22RG8AlruXTyn?usp=drive_link","a":"kevin","w":""},
  {"r":235,"p":"台南大豐段","d":"2026-06-18","n":"台南大豐段-門禁、訪客、停管 設備規劃繪製","u":"https://drive.google.com/drive/folders/1cGZu7lB6WyzpwW12pbw3t9w-4sUeCnia?usp=drive_link","a":"張友山","w":""},
  {"r":236,"p":"寶豐隆","d":"2026-06-17","n":"寶豐隆：計算在席線槽米數；底圖更新，更換底圖。\n停管門禁訪客架構圖、停管昇位圖、訪客門禁昇位圖","u":"https://drive.google.com/drive/folders/1-g8EBG0uNvkR4qb-CSomKtomoK-gxC_r?usp=drive_link","a":"張友山","w":""},
  {"r":237,"p":"錦中段","d":"2026-06-17","n":"錦中段：底圖更新，1F停管設備修改","u":"https://drive.google.com/file/d/1PgKBGGUtt9-3K-PWIC4sj_bB0WPj3GNt/view?usp=drive_link","a":"張友山","w":""},
  {"r":238,"p":"高雄四維財經大樓","d":"2026-06-18","n":"高雄四維財經大樓：繪製訪客門禁設備（B5F~27F）","u":"https://drive.google.com/file/d/1ZmAY7-ShIEoE441oxzr00ZZwKN1esHYj/view?usp=drive_link","a":"張友山","w":""},
  {"r":239,"p":"淡水新市段52","d":"2026-06-23","n":"淡水新市段52:停車場規劃繪圖","u":"https://drive.google.com/drive/folders/1bIbaMPvnGeHhtInVIPqRiKH_RV9YW0io?usp=drive_link","a":"Vincent","w":""},
  {"r":240,"p":"台中中港大樓","d":"2026-06-29","n":"台中中港大樓:訪客   門禁   停管 緊急對講機 昇位圖/架構圖","u":"https://drive.google.com/drive/folders/1DsNTEXKUaS2yFjjMSqSE4qUb1q3WoWqE?usp=drive_link","a":"張友山","w":""},
  {"r":241,"p":"宜蘭中華路","d":"2026-07-02","n":"宜蘭中華路:停車場規劃繪製","u":"https://drive.google.com/file/d/1GTVZ_vNjSfagZzgOFfwDlEUtJ6JXHP2b/view?usp=drive_link","a":"Vincent","w":""}
]);

function v21DrawingProgressSource20260814_() {
  return V21_DRAWING_PROGRESS_20260814.slice();
}
